# https://taskfile.dev

version: "3"

vars:
  VERSION: 0.7.5
  
interval: 200ms

tasks:
  libpub:
    cmds:
      - git push origin
      - git tag v{{.VERSION}}
      - git push --tags
      - GOPROXY=proxy.golang.org go list -m github.com/delaneyj/toolbelt@v{{.VERSION}}

  install-jtd:
    desc: Install the JTD to Go generator
    dir: jtd/cmd/jtd2go
    cmds:
      - go install .

  install-pixel2svg:
    desc: Install the pixel2svg tool
    dir: pixel2svg
    cmds:
      - go install .

  install-sqlc-gen-zombiezen:
    desc: Install the sqlc zombiezen plugin
    dir: sqlc-gen-zombiezen
    cmds:
      - go install .
