// Code generated by qtc from "crud.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line crud.qtpl:1
package zombiezen

//line crud.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line crud.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line crud.qtpl:1
func StreamGenerateCRUD(qw422016 *qt422016.Writer, t *GenerateCRUDTable) {
//line crud.qtpl:1
	qw422016.N().S(`
// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package `)
//line crud.qtpl:4
	qw422016.E().S(t.PackageName.Lower)
//line crud.qtpl:4
	qw422016.N().S(`

import (
    "fmt"
    `)
//line crud.qtpl:8
	if t.NeedsTimePackage {
//line crud.qtpl:8
		qw422016.N().S(`"time"`)
//line crud.qtpl:8
	}
//line crud.qtpl:8
	qw422016.N().S(`
    "zombiezen.com/go/sqlite"
    `)
//line crud.qtpl:10
	if t.NeedsToolbelt {
//line crud.qtpl:10
		qw422016.N().S(`"github.com/delaneyj/toolbelt"`)
//line crud.qtpl:10
	}
//line crud.qtpl:10
	qw422016.N().S(`
)

type `)
//line crud.qtpl:13
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:13
	qw422016.N().S(`Model struct {
`)
//line crud.qtpl:14
	for _, f := range t.Fields {
//line crud.qtpl:14
		qw422016.N().S(`        `)
//line crud.qtpl:15
		qw422016.E().S(f.Name.Pascal)
//line crud.qtpl:15
		qw422016.N().S(` `)
//line crud.qtpl:15
		if f.IsNullable {
//line crud.qtpl:15
			qw422016.N().S(`*`)
//line crud.qtpl:15
		}
//line crud.qtpl:15
		qw422016.E().S(f.GoType.Original)
//line crud.qtpl:15
		qw422016.N().S(` `)
//line crud.qtpl:15
		qw422016.N().S("`")
//line crud.qtpl:15
		qw422016.N().S(`json:"`)
//line crud.qtpl:15
		qw422016.E().S(f.Name.Lower)
//line crud.qtpl:15
		qw422016.N().S(`"`)
//line crud.qtpl:15
		qw422016.N().S("`")
//line crud.qtpl:15
		qw422016.N().S(`
`)
//line crud.qtpl:16
	}
//line crud.qtpl:16
	qw422016.N().S(`}


type Create`)
//line crud.qtpl:20
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:20
	qw422016.N().S(`Stmt struct {
    stmt *sqlite.Stmt
}

func Create`)
//line crud.qtpl:24
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:24
	qw422016.N().S(`(tx *sqlite.Conn) *Create`)
//line crud.qtpl:24
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:24
	qw422016.N().S(`Stmt {
    stmt := tx.Prep(`)
//line crud.qtpl:24
	qw422016.N().S("`")
//line crud.qtpl:24
	qw422016.N().S(`
INSERT INTO `)
//line crud.qtpl:26
	qw422016.E().S(t.Name.Lower)
//line crud.qtpl:26
	qw422016.N().S(` (
`)
//line crud.qtpl:27
	for i, f := range t.Fields {
//line crud.qtpl:27
		qw422016.N().S(`        `)
//line crud.qtpl:28
		qw422016.E().S(f.Name.Lower)
//line crud.qtpl:28
		if i < len(t.Fields)-1 {
//line crud.qtpl:28
			qw422016.N().S(`,`)
//line crud.qtpl:28
		}
//line crud.qtpl:28
		qw422016.N().S(`
`)
//line crud.qtpl:29
	}
//line crud.qtpl:29
	qw422016.N().S(`) VALUES (
`)
//line crud.qtpl:31
	for i := range t.Fields {
//line crud.qtpl:31
		qw422016.N().S(`        ?`)
//line crud.qtpl:32
		if i < len(t.Fields)-1 {
//line crud.qtpl:32
			qw422016.N().S(`,`)
//line crud.qtpl:32
		}
//line crud.qtpl:32
		qw422016.N().S(`
`)
//line crud.qtpl:33
	}
//line crud.qtpl:33
	qw422016.N().S(`)
    `)
//line crud.qtpl:33
	qw422016.N().S("`")
//line crud.qtpl:33
	qw422016.N().S(`)
    return &Create`)
//line crud.qtpl:36
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:36
	qw422016.N().S(`Stmt{stmt: stmt}
}

func (ps *Create`)
//line crud.qtpl:39
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:39
	qw422016.N().S(`Stmt) Run(m *`)
//line crud.qtpl:39
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:39
	qw422016.N().S(`Model) error {
    defer ps.stmt.Reset()

    // Bind parameters
    `)
//line crud.qtpl:43
	streambindFields(qw422016, t)
//line crud.qtpl:43
	qw422016.N().S(`

    if _, err := ps.stmt.Step(); err != nil {
        return fmt.Errorf("failed to insert `)
//line crud.qtpl:46
	qw422016.E().S(t.Name.Lower)
//line crud.qtpl:46
	qw422016.N().S(`: %w", err)
    }

    return nil
}

func OnceCreate`)
//line crud.qtpl:52
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:52
	qw422016.N().S(`(tx *sqlite.Conn, m *`)
//line crud.qtpl:52
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:52
	qw422016.N().S(`Model) error {
    ps := Create`)
//line crud.qtpl:53
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:53
	qw422016.N().S(`(tx)
    return ps.Run(m)
}

type ReadAll`)
//line crud.qtpl:57
	qw422016.E().S(t.Name.Pascal)
//line crud.qtpl:57
	qw422016.N().S(`Stmt struct {
    stmt *sqlite.Stmt
}

func ReadAll`)
//line crud.qtpl:61
	qw422016.E().S(t.Name.Pascal)
//line crud.qtpl:61
	qw422016.N().S(`(tx *sqlite.Conn) *ReadAll`)
//line crud.qtpl:61
	qw422016.E().S(t.Name.Pascal)
//line crud.qtpl:61
	qw422016.N().S(`Stmt {
    stmt := tx.Prep(`)
//line crud.qtpl:61
	qw422016.N().S("`")
//line crud.qtpl:61
	qw422016.N().S(`
SELECT
`)
//line crud.qtpl:64
	for i, f := range t.Fields {
//line crud.qtpl:64
		qw422016.N().S(`        `)
//line crud.qtpl:65
		qw422016.E().S(f.Name.Lower)
//line crud.qtpl:65
		if i < len(t.Fields)-1 {
//line crud.qtpl:65
			qw422016.N().S(`,`)
//line crud.qtpl:65
		}
//line crud.qtpl:65
		qw422016.N().S(`
`)
//line crud.qtpl:66
	}
//line crud.qtpl:66
	qw422016.N().S(`FROM `)
//line crud.qtpl:67
	qw422016.E().S(t.Name.Lower)
//line crud.qtpl:67
	qw422016.N().S(`
    `)
//line crud.qtpl:67
	qw422016.N().S("`")
//line crud.qtpl:67
	qw422016.N().S(`)
    return &ReadAll`)
//line crud.qtpl:69
	qw422016.E().S(t.Name.Pascal)
//line crud.qtpl:69
	qw422016.N().S(`Stmt{stmt: stmt}
}

func (ps *ReadAll`)
//line crud.qtpl:72
	qw422016.E().S(t.Name.Pascal)
//line crud.qtpl:72
	qw422016.N().S(`Stmt) Run() ([]*`)
//line crud.qtpl:72
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:72
	qw422016.N().S(`Model, error) {
    defer ps.stmt.Reset()

    var models []*`)
//line crud.qtpl:75
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:75
	qw422016.N().S(`Model
    for {
        hasRow, err := ps.stmt.Step()
        if err != nil {
            return nil, fmt.Errorf("failed to read `)
//line crud.qtpl:79
	qw422016.E().S(t.Name.Lower)
//line crud.qtpl:79
	qw422016.N().S(`: %w", err)
        } else if !hasRow {
            break
        }

        m := &`)
//line crud.qtpl:84
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:84
	qw422016.N().S(`Model{}
        `)
//line crud.qtpl:85
	streamfillResStruct(qw422016, t)
//line crud.qtpl:85
	qw422016.N().S(`

        models = append(models, m)
    }

    return models, nil
}

func OnceReadAll`)
//line crud.qtpl:93
	qw422016.E().S(t.Name.Pascal)
//line crud.qtpl:93
	qw422016.N().S(`(tx *sqlite.Conn) ([]*`)
//line crud.qtpl:93
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:93
	qw422016.N().S(`Model, error) {
    ps := ReadAll`)
//line crud.qtpl:94
	qw422016.E().S(t.Name.Pascal)
//line crud.qtpl:94
	qw422016.N().S(`(tx)
    return ps.Run()
}

`)
//line crud.qtpl:98
	if t.HasID {
//line crud.qtpl:98
		qw422016.N().S(`type ReadByID`)
//line crud.qtpl:99
		qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:99
		qw422016.N().S(`Stmt struct {
    stmt *sqlite.Stmt
}

func ReadByID`)
//line crud.qtpl:103
		qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:103
		qw422016.N().S(`(tx *sqlite.Conn) *ReadByID`)
//line crud.qtpl:103
		qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:103
		qw422016.N().S(`Stmt {
    stmt := tx.Prep(`)
//line crud.qtpl:103
		qw422016.N().S("`")
//line crud.qtpl:103
		qw422016.N().S(`
SELECT
`)
//line crud.qtpl:106
		for i, f := range t.Fields {
//line crud.qtpl:106
			qw422016.N().S(`        `)
//line crud.qtpl:107
			qw422016.E().S(f.Name.Lower)
//line crud.qtpl:107
			if i < len(t.Fields)-1 {
//line crud.qtpl:107
				qw422016.N().S(`,`)
//line crud.qtpl:107
			}
//line crud.qtpl:107
			qw422016.N().S(`
`)
//line crud.qtpl:108
		}
//line crud.qtpl:108
		qw422016.N().S(`FROM `)
//line crud.qtpl:109
		qw422016.E().S(t.Name.Lower)
//line crud.qtpl:109
		qw422016.N().S(`
WHERE id = ?
    `)
//line crud.qtpl:109
		qw422016.N().S("`")
//line crud.qtpl:109
		qw422016.N().S(`)
    return &ReadByID`)
//line crud.qtpl:112
		qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:112
		qw422016.N().S(`Stmt{stmt: stmt}
}

func (ps *ReadByID`)
//line crud.qtpl:115
		qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:115
		qw422016.N().S(`Stmt) Run(id int64) (*`)
//line crud.qtpl:115
		qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:115
		qw422016.N().S(`Model, error) {
    defer ps.stmt.Reset()

    ps.stmt.BindInt64(1, id)

    if hasRow, err := ps.stmt.Step(); err != nil {
        return nil, fmt.Errorf("failed to read `)
//line crud.qtpl:121
		qw422016.E().S(t.Name.Lower)
//line crud.qtpl:121
		qw422016.N().S(`: %w", err)
    } else if !hasRow {
        return nil, nil
    }

    m := &`)
//line crud.qtpl:126
		qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:126
		qw422016.N().S(`Model{}
    `)
//line crud.qtpl:127
		streamfillResStruct(qw422016, t)
//line crud.qtpl:127
		qw422016.N().S(`

    return m, nil
}

func OnceReadByID`)
//line crud.qtpl:132
		qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:132
		qw422016.N().S(`(tx *sqlite.Conn, id int64) (*`)
//line crud.qtpl:132
		qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:132
		qw422016.N().S(`Model, error) {
    ps := ReadByID`)
//line crud.qtpl:133
		qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:133
		qw422016.N().S(`(tx)
    return ps.Run(id)
}
`)
//line crud.qtpl:136
	}
//line crud.qtpl:136
	qw422016.N().S(`
func Count`)
//line crud.qtpl:138
	qw422016.E().S(t.Name.Pascal)
//line crud.qtpl:138
	qw422016.N().S(`(tx *sqlite.Conn) (int64, error) {
    stmt := tx.Prep(`)
//line crud.qtpl:138
	qw422016.N().S("`")
//line crud.qtpl:138
	qw422016.N().S(`
SELECT COUNT(*)
FROM `)
//line crud.qtpl:141
	qw422016.E().S(t.Name.Lower)
//line crud.qtpl:141
	qw422016.N().S(`
    `)
//line crud.qtpl:141
	qw422016.N().S("`")
//line crud.qtpl:141
	qw422016.N().S(`)
    defer stmt.Reset()

    if hasRow, err := stmt.Step(); err != nil {
        return 0, fmt.Errorf("failed to count `)
//line crud.qtpl:146
	qw422016.E().S(t.Name.Lower)
//line crud.qtpl:146
	qw422016.N().S(`: %w", err)
    } else if !hasRow {
        return 0, nil
    }

    return stmt.ColumnInt64(0), nil
}

func OnceCount`)
//line crud.qtpl:154
	qw422016.E().S(t.Name.Pascal)
//line crud.qtpl:154
	qw422016.N().S(`(tx *sqlite.Conn) (int64, error) {
    return Count`)
//line crud.qtpl:155
	qw422016.E().S(t.Name.Pascal)
//line crud.qtpl:155
	qw422016.N().S(`(tx)
}

type Update`)
//line crud.qtpl:158
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:158
	qw422016.N().S(`Stmt struct {
    stmt *sqlite.Stmt
}

func Update`)
//line crud.qtpl:162
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:162
	qw422016.N().S(`(tx *sqlite.Conn) *Update`)
//line crud.qtpl:162
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:162
	qw422016.N().S(`Stmt {
    stmt := tx.Prep(`)
//line crud.qtpl:162
	qw422016.N().S("`")
//line crud.qtpl:162
	qw422016.N().S(`
UPDATE `)
//line crud.qtpl:164
	qw422016.E().S(t.Name.Lower)
//line crud.qtpl:164
	qw422016.N().S(`
SET
`)
//line crud.qtpl:166
	for i, f := range t.Fields {
//line crud.qtpl:167
		if i > 0 {
//line crud.qtpl:167
			qw422016.N().S(`        `)
//line crud.qtpl:168
			qw422016.E().S(f.Name.Lower)
//line crud.qtpl:168
			qw422016.N().S(` = ?`)
//line crud.qtpl:168
			qw422016.N().D(i + 1)
//line crud.qtpl:168
			if i < len(t.Fields)-1 {
//line crud.qtpl:168
				qw422016.N().S(`,`)
//line crud.qtpl:168
			}
//line crud.qtpl:168
			qw422016.N().S(`
`)
//line crud.qtpl:169
		}
//line crud.qtpl:170
	}
//line crud.qtpl:170
	qw422016.N().S(`WHERE id = ?1
    `)
//line crud.qtpl:170
	qw422016.N().S("`")
//line crud.qtpl:170
	qw422016.N().S(`)
    return &Update`)
//line crud.qtpl:173
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:173
	qw422016.N().S(`Stmt{stmt: stmt}
}

func (ps *Update`)
//line crud.qtpl:176
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:176
	qw422016.N().S(`Stmt) Run(m *`)
//line crud.qtpl:176
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:176
	qw422016.N().S(`Model) error {
    defer ps.stmt.Reset()

    // Bind parameters
    `)
//line crud.qtpl:180
	streambindFields(qw422016, t)
//line crud.qtpl:180
	qw422016.N().S(`

    if _, err := ps.stmt.Step(); err != nil {
        return fmt.Errorf("failed to update `)
//line crud.qtpl:183
	qw422016.E().S(t.Name.Lower)
//line crud.qtpl:183
	qw422016.N().S(`: %w", err)
    }

    return nil
}

func OnceUpdate`)
//line crud.qtpl:189
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:189
	qw422016.N().S(`(tx *sqlite.Conn, m *`)
//line crud.qtpl:189
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:189
	qw422016.N().S(`Model) error {
    ps := Update`)
//line crud.qtpl:190
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:190
	qw422016.N().S(`(tx)
    return ps.Run(m)
}

type Delete`)
//line crud.qtpl:194
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:194
	qw422016.N().S(`Stmt struct {
    stmt *sqlite.Stmt
}

func Delete`)
//line crud.qtpl:198
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:198
	qw422016.N().S(`(tx *sqlite.Conn) *Delete`)
//line crud.qtpl:198
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:198
	qw422016.N().S(`Stmt {
    stmt := tx.Prep(`)
//line crud.qtpl:198
	qw422016.N().S("`")
//line crud.qtpl:198
	qw422016.N().S(`
DELETE FROM `)
//line crud.qtpl:200
	qw422016.E().S(t.Name.Lower)
//line crud.qtpl:200
	qw422016.N().S(`
WHERE id = ?
    `)
//line crud.qtpl:200
	qw422016.N().S("`")
//line crud.qtpl:200
	qw422016.N().S(`)
    return &Delete`)
//line crud.qtpl:203
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:203
	qw422016.N().S(`Stmt{stmt: stmt}
}

func (ps *Delete`)
//line crud.qtpl:206
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:206
	qw422016.N().S(`Stmt) Run(id int64) error {
    defer ps.stmt.Reset()

    ps.stmt.BindInt64(1, id)

    if _, err := ps.stmt.Step(); err != nil {
        return fmt.Errorf("failed to delete `)
//line crud.qtpl:212
	qw422016.E().S(t.Name.Lower)
//line crud.qtpl:212
	qw422016.N().S(`: %w", err)
    }

    return nil
}

func OnceDelete`)
//line crud.qtpl:218
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:218
	qw422016.N().S(`(tx *sqlite.Conn, id int64) error {
    ps := Delete`)
//line crud.qtpl:219
	qw422016.E().S(t.SingleName.Pascal)
//line crud.qtpl:219
	qw422016.N().S(`(tx)
    return ps.Run(id)
}

`)
//line crud.qtpl:223
}

//line crud.qtpl:223
func WriteGenerateCRUD(qq422016 qtio422016.Writer, t *GenerateCRUDTable) {
//line crud.qtpl:223
	qw422016 := qt422016.AcquireWriter(qq422016)
//line crud.qtpl:223
	StreamGenerateCRUD(qw422016, t)
//line crud.qtpl:223
	qt422016.ReleaseWriter(qw422016)
//line crud.qtpl:223
}

//line crud.qtpl:223
func GenerateCRUD(t *GenerateCRUDTable) string {
//line crud.qtpl:223
	qb422016 := qt422016.AcquireByteBuffer()
//line crud.qtpl:223
	WriteGenerateCRUD(qb422016, t)
//line crud.qtpl:223
	qs422016 := string(qb422016.B)
//line crud.qtpl:223
	qt422016.ReleaseByteBuffer(qb422016)
//line crud.qtpl:223
	return qs422016
//line crud.qtpl:223
}

//line crud.qtpl:225
func streambindFields(qw422016 *qt422016.Writer, tbl *GenerateCRUDTable) {
//line crud.qtpl:226
	for _, f := range tbl.Fields {
//line crud.qtpl:227
		if f.IsNullable {
//line crud.qtpl:227
			qw422016.N().S(`    if m.`)
//line crud.qtpl:228
			qw422016.E().S(f.Name.Pascal)
//line crud.qtpl:228
			qw422016.N().S(` == nil {
        ps.stmt.BindNull(`)
//line crud.qtpl:229
			qw422016.N().D(f.Column)
//line crud.qtpl:229
			qw422016.N().S(`)
    } else {
        `)
//line crud.qtpl:231
			streambindField(qw422016, f, true)
//line crud.qtpl:231
			qw422016.N().S(`    }
`)
//line crud.qtpl:233
		} else {
//line crud.qtpl:233
			qw422016.N().S(`    `)
//line crud.qtpl:234
			streambindField(qw422016, f, false)
//line crud.qtpl:234
			qw422016.N().S(`
`)
//line crud.qtpl:235
		}
//line crud.qtpl:236
	}
//line crud.qtpl:237
}

//line crud.qtpl:237
func writebindFields(qq422016 qtio422016.Writer, tbl *GenerateCRUDTable) {
//line crud.qtpl:237
	qw422016 := qt422016.AcquireWriter(qq422016)
//line crud.qtpl:237
	streambindFields(qw422016, tbl)
//line crud.qtpl:237
	qt422016.ReleaseWriter(qw422016)
//line crud.qtpl:237
}

//line crud.qtpl:237
func bindFields(tbl *GenerateCRUDTable) string {
//line crud.qtpl:237
	qb422016 := qt422016.AcquireByteBuffer()
//line crud.qtpl:237
	writebindFields(qb422016, tbl)
//line crud.qtpl:237
	qs422016 := string(qb422016.B)
//line crud.qtpl:237
	qt422016.ReleaseByteBuffer(qb422016)
//line crud.qtpl:237
	return qs422016
//line crud.qtpl:237
}

//line crud.qtpl:239
func streambindField(qw422016 *qt422016.Writer, f GenerateField, isNullable bool) {
//line crud.qtpl:239
	qw422016.N().S(`    ps.`)
//line crud.qtpl:240
	switch f.GoType.Original {
//line crud.qtpl:241
	case "time.Time":
//line crud.qtpl:241
		qw422016.N().S(`            stmt.Bind`)
//line crud.qtpl:242
		qw422016.E().S(f.SQLType.Pascal)
//line crud.qtpl:242
		qw422016.N().S(`(`)
//line crud.qtpl:242
		qw422016.N().D(f.Column)
//line crud.qtpl:242
		qw422016.N().S(`, toolbelt.TimeToJulianDay(`)
//line crud.qtpl:242
		if isNullable {
//line crud.qtpl:242
			qw422016.N().S(`*`)
//line crud.qtpl:242
		}
//line crud.qtpl:242
		qw422016.N().S(` m.`)
//line crud.qtpl:242
		qw422016.E().S(f.Name.Pascal)
//line crud.qtpl:242
		qw422016.N().S(`))
`)
//line crud.qtpl:243
	case "time.Duration":
//line crud.qtpl:244
		if f.DurationFromText {
//line crud.qtpl:244
			qw422016.N().S(`            stmt.BindText(`)
//line crud.qtpl:245
			qw422016.N().D(f.Column)
//line crud.qtpl:245
			qw422016.N().S(`, `)
//line crud.qtpl:245
			if isNullable {
//line crud.qtpl:245
				qw422016.N().S(`(*`)
//line crud.qtpl:245
			}
//line crud.qtpl:245
			qw422016.N().S(`m.`)
//line crud.qtpl:245
			qw422016.E().S(f.Name.Pascal)
//line crud.qtpl:245
			if isNullable {
//line crud.qtpl:245
				qw422016.N().S(`)`)
//line crud.qtpl:245
			}
//line crud.qtpl:245
			qw422016.N().S(`.String())
`)
//line crud.qtpl:246
		} else {
//line crud.qtpl:246
			qw422016.N().S(`            stmt.Bind`)
//line crud.qtpl:247
			qw422016.E().S(f.SQLType.Pascal)
//line crud.qtpl:247
			qw422016.N().S(`(`)
//line crud.qtpl:247
			qw422016.N().D(f.Column)
//line crud.qtpl:247
			qw422016.N().S(`, toolbelt.DurationToMilliseconds(`)
//line crud.qtpl:247
			if isNullable {
//line crud.qtpl:247
				qw422016.N().S(`*`)
//line crud.qtpl:247
			}
//line crud.qtpl:247
			qw422016.N().S(`m.`)
//line crud.qtpl:247
			qw422016.E().S(f.Name.Pascal)
//line crud.qtpl:247
			qw422016.N().S(`))
`)
//line crud.qtpl:248
		}
//line crud.qtpl:249
	default:
//line crud.qtpl:249
		qw422016.N().S(`            stmt.Bind`)
//line crud.qtpl:250
		qw422016.E().S(f.SQLType.Pascal)
//line crud.qtpl:250
		qw422016.N().S(`(`)
//line crud.qtpl:250
		qw422016.N().D(f.Column)
//line crud.qtpl:250
		qw422016.N().S(`, `)
//line crud.qtpl:250
		if isNullable {
//line crud.qtpl:250
			qw422016.N().S(`*`)
//line crud.qtpl:250
		}
//line crud.qtpl:250
		qw422016.N().S(`m.`)
//line crud.qtpl:250
		qw422016.E().S(f.Name.Pascal)
//line crud.qtpl:250
		qw422016.N().S(`)
`)
//line crud.qtpl:251
	}
//line crud.qtpl:252
}

//line crud.qtpl:252
func writebindField(qq422016 qtio422016.Writer, f GenerateField, isNullable bool) {
//line crud.qtpl:252
	qw422016 := qt422016.AcquireWriter(qq422016)
//line crud.qtpl:252
	streambindField(qw422016, f, isNullable)
//line crud.qtpl:252
	qt422016.ReleaseWriter(qw422016)
//line crud.qtpl:252
}

//line crud.qtpl:252
func bindField(f GenerateField, isNullable bool) string {
//line crud.qtpl:252
	qb422016 := qt422016.AcquireByteBuffer()
//line crud.qtpl:252
	writebindField(qb422016, f, isNullable)
//line crud.qtpl:252
	qs422016 := string(qb422016.B)
//line crud.qtpl:252
	qt422016.ReleaseByteBuffer(qb422016)
//line crud.qtpl:252
	return qs422016
//line crud.qtpl:252
}

//line crud.qtpl:254
func streamfillResStruct(qw422016 *qt422016.Writer, t *GenerateCRUDTable) {
//line crud.qtpl:255
	for i, f := range t.Fields {
//line crud.qtpl:256
		if f.IsNullable {
//line crud.qtpl:256
			qw422016.N().S(`
    if ps.stmt.ColumnIsNull(`)
//line crud.qtpl:257
			qw422016.N().D(i)
//line crud.qtpl:257
			qw422016.N().S(`) {
        m.`)
//line crud.qtpl:258
			qw422016.E().S(f.Name.Pascal)
//line crud.qtpl:258
			qw422016.N().S(` = nil
    } else {
`)
//line crud.qtpl:260
			if f.GoType.Original == "time.Duration" && f.DurationFromText {
//line crud.qtpl:260
				qw422016.N().S(`
        durStr := ps.stmt.ColumnText(`)
//line crud.qtpl:261
				qw422016.N().D(i)
//line crud.qtpl:261
				qw422016.N().S(`)
        dur, err := time.ParseDuration(durStr)
        if err != nil {
            return nil, fmt.Errorf("parsing `)
//line crud.qtpl:264
				qw422016.E().S(t.Name.Lower)
//line crud.qtpl:264
				qw422016.N().S(`.`)
//line crud.qtpl:264
				qw422016.E().S(f.Name.Lower)
//line crud.qtpl:264
				qw422016.N().S(`: %w", err)
        }
        m.`)
//line crud.qtpl:266
				qw422016.E().S(f.Name.Pascal)
//line crud.qtpl:266
				qw422016.N().S(` = &dur
`)
//line crud.qtpl:267
			} else {
//line crud.qtpl:267
				qw422016.N().S(`
        tmp := `)
//line crud.qtpl:268
				streamfillResStructField(qw422016, f, i)
//line crud.qtpl:268
				qw422016.N().S(`
        m.`)
//line crud.qtpl:269
				qw422016.E().S(f.Name.Pascal)
//line crud.qtpl:269
				qw422016.N().S(` = &tmp
`)
//line crud.qtpl:270
			}
//line crud.qtpl:270
			qw422016.N().S(`
    }
`)
//line crud.qtpl:272
		} else {
//line crud.qtpl:272
			qw422016.N().S(`
`)
//line crud.qtpl:273
			if f.GoType.Original == "time.Duration" && f.DurationFromText {
//line crud.qtpl:273
				qw422016.N().S(`
    durStr := ps.stmt.ColumnText(`)
//line crud.qtpl:274
				qw422016.N().D(i)
//line crud.qtpl:274
				qw422016.N().S(`)
    dur, err := time.ParseDuration(durStr)
    if err != nil {
        return nil, fmt.Errorf("parsing `)
//line crud.qtpl:277
				qw422016.E().S(t.Name.Lower)
//line crud.qtpl:277
				qw422016.N().S(`.`)
//line crud.qtpl:277
				qw422016.E().S(f.Name.Lower)
//line crud.qtpl:277
				qw422016.N().S(`: %w", err)
    }
    m.`)
//line crud.qtpl:279
				qw422016.E().S(f.Name.Pascal)
//line crud.qtpl:279
				qw422016.N().S(` = dur
`)
//line crud.qtpl:280
			} else {
//line crud.qtpl:280
				qw422016.N().S(`
    m.`)
//line crud.qtpl:281
				qw422016.E().S(f.Name.Pascal)
//line crud.qtpl:281
				qw422016.N().S(` = `)
//line crud.qtpl:281
				streamfillResStructField(qw422016, f, i)
//line crud.qtpl:281
				qw422016.N().S(`
`)
//line crud.qtpl:282
			}
//line crud.qtpl:282
			qw422016.N().S(`
`)
//line crud.qtpl:283
		}
//line crud.qtpl:283
		qw422016.N().S(`
`)
//line crud.qtpl:284
	}
//line crud.qtpl:285
}

//line crud.qtpl:285
func writefillResStruct(qq422016 qtio422016.Writer, t *GenerateCRUDTable) {
//line crud.qtpl:285
	qw422016 := qt422016.AcquireWriter(qq422016)
//line crud.qtpl:285
	streamfillResStruct(qw422016, t)
//line crud.qtpl:285
	qt422016.ReleaseWriter(qw422016)
//line crud.qtpl:285
}

//line crud.qtpl:285
func fillResStruct(t *GenerateCRUDTable) string {
//line crud.qtpl:285
	qb422016 := qt422016.AcquireByteBuffer()
//line crud.qtpl:285
	writefillResStruct(qb422016, t)
//line crud.qtpl:285
	qs422016 := string(qb422016.B)
//line crud.qtpl:285
	qt422016.ReleaseByteBuffer(qb422016)
//line crud.qtpl:285
	return qs422016
//line crud.qtpl:285
}

//line crud.qtpl:287
func streamfillResStructField(qw422016 *qt422016.Writer, f GenerateField, i int) {
//line crud.qtpl:288
	switch f.GoType.Original {
//line crud.qtpl:289
	case "time.Time":
//line crud.qtpl:289
		qw422016.N().S(`            toolbelt.JulianDayToTime(ps.stmt.Column`)
//line crud.qtpl:290
		qw422016.E().S(f.SQLType.Pascal)
//line crud.qtpl:290
		qw422016.N().S(`(`)
//line crud.qtpl:290
		qw422016.N().D(i)
//line crud.qtpl:290
		qw422016.N().S(`))
`)
//line crud.qtpl:291
	case "time.Duration":
//line crud.qtpl:291
		qw422016.N().S(`            toolbelt.MillisecondsToDuration(ps.stmt.Column`)
//line crud.qtpl:292
		qw422016.E().S(f.SQLType.Pascal)
//line crud.qtpl:292
		qw422016.N().S(`(`)
//line crud.qtpl:292
		qw422016.N().D(i)
//line crud.qtpl:292
		qw422016.N().S(`))
`)
//line crud.qtpl:293
	case "[]byte":
//line crud.qtpl:293
		qw422016.N().S(`            toolbelt.StmtBytesByCol(ps.stmt, `)
//line crud.qtpl:294
		qw422016.N().D(i)
//line crud.qtpl:294
		qw422016.N().S(`)
`)
//line crud.qtpl:295
	default:
//line crud.qtpl:295
		qw422016.N().S(`            ps.stmt.Column`)
//line crud.qtpl:296
		qw422016.E().S(f.SQLType.Pascal)
//line crud.qtpl:296
		qw422016.N().S(`(`)
//line crud.qtpl:296
		qw422016.N().D(i)
//line crud.qtpl:296
		qw422016.N().S(`)
`)
//line crud.qtpl:297
	}
//line crud.qtpl:298
}

//line crud.qtpl:298
func writefillResStructField(qq422016 qtio422016.Writer, f GenerateField, i int) {
//line crud.qtpl:298
	qw422016 := qt422016.AcquireWriter(qq422016)
//line crud.qtpl:298
	streamfillResStructField(qw422016, f, i)
//line crud.qtpl:298
	qt422016.ReleaseWriter(qw422016)
//line crud.qtpl:298
}

//line crud.qtpl:298
func fillResStructField(f GenerateField, i int) string {
//line crud.qtpl:298
	qb422016 := qt422016.AcquireByteBuffer()
//line crud.qtpl:298
	writefillResStructField(qb422016, f, i)
//line crud.qtpl:298
	qs422016 := string(qb422016.B)
//line crud.qtpl:298
	qt422016.ReleaseByteBuffer(qb422016)
//line crud.qtpl:298
	return qs422016
//line crud.qtpl:298
}
