// Code generated by qtc from "queries.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line zombiezen/queries.qtpl:1
package zombiezen

//line zombiezen/queries.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line zombiezen/queries.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line zombiezen/queries.qtpl:1
func StreamGenerateQuery(qw422016 *qt422016.Writer, q *GenerateQueryContext) {
//line zombiezen/queries.qtpl:1
	qw422016.N().S(`
// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package `)
//line zombiezen/queries.qtpl:4
	qw422016.E().S(q.PackageName.Lower)
//line zombiezen/queries.qtpl:4
	qw422016.N().S(`

import (
    "fmt"
    "zombiezen.com/go/sqlite"

    `)
//line zombiezen/queries.qtpl:10
	if q.HasSliceParams {
//line zombiezen/queries.qtpl:10
		qw422016.N().S(`
    "strings"
    `)
//line zombiezen/queries.qtpl:12
	}
//line zombiezen/queries.qtpl:12
	qw422016.N().S(`

    `)
//line zombiezen/queries.qtpl:14
	if q.NeedsTimePackage {
//line zombiezen/queries.qtpl:14
		qw422016.N().S(`
    "time"
    "github.com/delaneyj/toolbelt"
    `)
//line zombiezen/queries.qtpl:17
	}
//line zombiezen/queries.qtpl:17
	qw422016.N().S(`
)

`)
//line zombiezen/queries.qtpl:20
	if q.HasResponse && !q.ResponseIsSingularField {
//line zombiezen/queries.qtpl:20
		qw422016.N().S(`
type `)
//line zombiezen/queries.qtpl:21
		qw422016.E().S(q.Name.Pascal)
//line zombiezen/queries.qtpl:21
		qw422016.N().S(`Res struct {
`)
//line zombiezen/queries.qtpl:22
		for _, f := range q.ResponseFields {
//line zombiezen/queries.qtpl:22
			qw422016.N().S(`        `)
//line zombiezen/queries.qtpl:23
			qw422016.E().S(f.Name.Pascal)
//line zombiezen/queries.qtpl:23
			qw422016.N().S(` `)
//line zombiezen/queries.qtpl:23
			if f.IsNullable {
//line zombiezen/queries.qtpl:23
				qw422016.N().S(`*`)
//line zombiezen/queries.qtpl:23
			}
//line zombiezen/queries.qtpl:23
			qw422016.E().S(f.GoType.Original)
//line zombiezen/queries.qtpl:23
			qw422016.N().S(` `)
//line zombiezen/queries.qtpl:23
			qw422016.N().S("`")
//line zombiezen/queries.qtpl:23
			qw422016.N().S(`json:"`)
//line zombiezen/queries.qtpl:23
			qw422016.E().S(f.Name.Lower)
//line zombiezen/queries.qtpl:23
			qw422016.N().S(`"`)
//line zombiezen/queries.qtpl:23
			qw422016.N().S("`")
//line zombiezen/queries.qtpl:23
			qw422016.N().S(`
`)
//line zombiezen/queries.qtpl:24
		}
//line zombiezen/queries.qtpl:24
		qw422016.N().S(`}
`)
//line zombiezen/queries.qtpl:26
	}
//line zombiezen/queries.qtpl:26
	qw422016.N().S(`

`)
//line zombiezen/queries.qtpl:28
	if q.HasParams && !q.ParamsIsSingularField {
//line zombiezen/queries.qtpl:28
		qw422016.N().S(`
type `)
//line zombiezen/queries.qtpl:29
		qw422016.E().S(q.Name.Pascal)
//line zombiezen/queries.qtpl:29
		qw422016.N().S(`Params struct {
`)
//line zombiezen/queries.qtpl:30
		for _, f := range q.Params {
//line zombiezen/queries.qtpl:30
			qw422016.N().S(`        `)
//line zombiezen/queries.qtpl:31
			qw422016.E().S(f.Name.Pascal)
//line zombiezen/queries.qtpl:31
			qw422016.N().S(` `)
//line zombiezen/queries.qtpl:31
			if f.IsNullable {
//line zombiezen/queries.qtpl:31
				qw422016.N().S(`*`)
//line zombiezen/queries.qtpl:31
			}
//line zombiezen/queries.qtpl:31
			qw422016.E().S(f.GoType.Original)
//line zombiezen/queries.qtpl:31
			qw422016.N().S(` `)
//line zombiezen/queries.qtpl:31
			qw422016.N().S("`")
//line zombiezen/queries.qtpl:31
			qw422016.N().S(`json:"`)
//line zombiezen/queries.qtpl:31
			qw422016.E().S(f.Name.Lower)
//line zombiezen/queries.qtpl:31
			qw422016.N().S(`"`)
//line zombiezen/queries.qtpl:31
			qw422016.N().S("`")
//line zombiezen/queries.qtpl:31
			qw422016.N().S(`
`)
//line zombiezen/queries.qtpl:32
		}
//line zombiezen/queries.qtpl:32
		qw422016.N().S(`}
`)
//line zombiezen/queries.qtpl:34
	}
//line zombiezen/queries.qtpl:34
	qw422016.N().S(`

type `)
//line zombiezen/queries.qtpl:36
	qw422016.E().S(q.Name.Pascal)
//line zombiezen/queries.qtpl:36
	qw422016.N().S(`Stmt struct {
    conn      *sqlite.Conn
    stmt      *sqlite.Stmt
    querySQL  string
    hasSlices bool
}

func `)
//line zombiezen/queries.qtpl:43
	qw422016.E().S(q.Name.Pascal)
//line zombiezen/queries.qtpl:43
	qw422016.N().S(`(tx *sqlite.Conn) *`)
//line zombiezen/queries.qtpl:43
	qw422016.E().S(q.Name.Pascal)
//line zombiezen/queries.qtpl:43
	qw422016.N().S(`Stmt {
    const querySQL = `)
//line zombiezen/queries.qtpl:43
	qw422016.N().S("`")
//line zombiezen/queries.qtpl:43
	qw422016.N().S(`
`)
//line zombiezen/queries.qtpl:45
	qw422016.N().S(q.SQL)
//line zombiezen/queries.qtpl:45
	qw422016.N().S(`
    `)
//line zombiezen/queries.qtpl:45
	qw422016.N().S("`")
//line zombiezen/queries.qtpl:45
	qw422016.N().S(`

    ps := &`)
//line zombiezen/queries.qtpl:48
	qw422016.E().S(q.Name.Pascal)
//line zombiezen/queries.qtpl:48
	qw422016.N().S(`Stmt{
        conn:     tx,
        querySQL: querySQL,
        hasSlices: `)
//line zombiezen/queries.qtpl:51
	if q.HasSliceParams {
//line zombiezen/queries.qtpl:51
		qw422016.N().S(`true`)
//line zombiezen/queries.qtpl:51
	} else {
//line zombiezen/queries.qtpl:51
		qw422016.N().S(`false`)
//line zombiezen/queries.qtpl:51
	}
//line zombiezen/queries.qtpl:51
	qw422016.N().S(`,
    }

    if !ps.hasSlices {
        ps.stmt = tx.Prep(querySQL)
    }

    return ps
}

func (ps *`)
//line zombiezen/queries.qtpl:61
	qw422016.E().S(q.Name.Pascal)
//line zombiezen/queries.qtpl:61
	qw422016.N().S(`Stmt) Run(
    `)
//line zombiezen/queries.qtpl:62
	streamfillReqParams(qw422016, q)
//line zombiezen/queries.qtpl:62
	qw422016.N().S(`) (
    `)
//line zombiezen/queries.qtpl:64
	streamfillReturns(qw422016, q)
//line zombiezen/queries.qtpl:64
	qw422016.N().S(`) {
    querySQL := ps.querySQL

`)
//line zombiezen/queries.qtpl:68
	if q.HasSliceParams {
//line zombiezen/queries.qtpl:68
		qw422016.N().S(`    `)
//line zombiezen/queries.qtpl:69
		streamdeclareSlices(qw422016, q, q.ParamsIsSingularField)
//line zombiezen/queries.qtpl:69
		qw422016.N().S(`
`)
//line zombiezen/queries.qtpl:70
	}
//line zombiezen/queries.qtpl:70
	qw422016.N().S(`
    var stmt *sqlite.Stmt
    if ps.hasSlices {
        stmt = ps.conn.Prep(querySQL)
    } else {
        stmt = ps.stmt
    }

    defer func() {
        _ = stmt.ClearBindings()
        _ = stmt.Reset()
    }()

`)
//line zombiezen/queries.qtpl:84
	if len(q.Params) > 0 {
//line zombiezen/queries.qtpl:84
		qw422016.N().S(`    bindIndex := 1
    // Bind parameters
    `)
//line zombiezen/queries.qtpl:87
		streambindParams(qw422016, q, q.ParamsIsSingularField)
//line zombiezen/queries.qtpl:87
		qw422016.N().S(`
`)
//line zombiezen/queries.qtpl:88
	}
//line zombiezen/queries.qtpl:88
	qw422016.N().S(`
    // Execute the query
`)
//line zombiezen/queries.qtpl:91
	if q.HasResponse {
//line zombiezen/queries.qtpl:92
		if q.ResponseHasMultiple {
//line zombiezen/queries.qtpl:92
			qw422016.N().S(`        for {
            if hasRow, err := stmt.Step(); err != nil {
                return res, fmt.Errorf("failed to execute {{.Name.Lower}} SQL: %w", err)
            } else if !hasRow {
                break
            }

`)
//line zombiezen/queries.qtpl:100
			if q.ResponseIsSingularField {
//line zombiezen/queries.qtpl:100
				qw422016.N().S(`            `)
//line zombiezen/queries.qtpl:101
				qw422016.E().S(q.ResponseFields[0].Name.Camel)
//line zombiezen/queries.qtpl:101
				qw422016.N().S(` := `)
//line zombiezen/queries.qtpl:101
				streamfillResponse(qw422016, q)
//line zombiezen/queries.qtpl:101
				qw422016.N().S(`            res = append(res, `)
//line zombiezen/queries.qtpl:102
				qw422016.E().S(q.ResponseFields[0].Name.Camel)
//line zombiezen/queries.qtpl:102
				qw422016.N().S(`)
`)
//line zombiezen/queries.qtpl:103
			} else {
//line zombiezen/queries.qtpl:103
				qw422016.N().S(`            `)
//line zombiezen/queries.qtpl:104
				streamfillResponse(qw422016, q)
//line zombiezen/queries.qtpl:104
				qw422016.N().S(`            res = append(res, row)
`)
//line zombiezen/queries.qtpl:106
			}
//line zombiezen/queries.qtpl:106
			qw422016.N().S(`        }
`)
//line zombiezen/queries.qtpl:108
		} else {
//line zombiezen/queries.qtpl:108
			qw422016.N().S(`        if hasRow, err := stmt.Step(); err != nil {
`)
//line zombiezen/queries.qtpl:110
			if q.ResponseIsSingularField {
//line zombiezen/queries.qtpl:110
				qw422016.N().S(`            return res, fmt.Errorf("failed to execute {{.Name.Lower}} SQL: %w", err)
`)
//line zombiezen/queries.qtpl:112
			} else {
//line zombiezen/queries.qtpl:112
				qw422016.N().S(`            return res, fmt.Errorf("failed to execute {{.Name.Lower}} SQL: %w", err)
`)
//line zombiezen/queries.qtpl:114
			}
//line zombiezen/queries.qtpl:114
			qw422016.N().S(`        } else if hasRow {
`)
//line zombiezen/queries.qtpl:116
			if q.ResponseIsSingularField {
//line zombiezen/queries.qtpl:116
				qw422016.N().S(`            res = `)
//line zombiezen/queries.qtpl:117
				streamfillResponse(qw422016, q)
//line zombiezen/queries.qtpl:118
			} else {
//line zombiezen/queries.qtpl:118
				qw422016.N().S(`            `)
//line zombiezen/queries.qtpl:119
				streamfillResponse(qw422016, q)
//line zombiezen/queries.qtpl:119
				qw422016.N().S(`            res = &row
`)
//line zombiezen/queries.qtpl:121
			}
//line zombiezen/queries.qtpl:121
			qw422016.N().S(`        }
`)
//line zombiezen/queries.qtpl:123
		}
//line zombiezen/queries.qtpl:124
	} else {
//line zombiezen/queries.qtpl:124
		qw422016.N().S(`    if _, err := stmt.Step(); err != nil {
        return fmt.Errorf("failed to execute `)
//line zombiezen/queries.qtpl:126
		qw422016.E().S(q.Name.Lower)
//line zombiezen/queries.qtpl:126
		qw422016.N().S(` SQL: %w", err)
    }
`)
//line zombiezen/queries.qtpl:128
	}
//line zombiezen/queries.qtpl:128
	qw422016.N().S(`
`)
//line zombiezen/queries.qtpl:130
	if q.HasResponse {
//line zombiezen/queries.qtpl:130
		qw422016.N().S(`    return res, nil
`)
//line zombiezen/queries.qtpl:132
	} else {
//line zombiezen/queries.qtpl:132
		qw422016.N().S(`    return nil
`)
//line zombiezen/queries.qtpl:134
	}
//line zombiezen/queries.qtpl:134
	qw422016.N().S(`}

func Once`)
//line zombiezen/queries.qtpl:137
	qw422016.E().S(q.Name.Pascal)
//line zombiezen/queries.qtpl:137
	qw422016.N().S(`(
    tx *sqlite.Conn,
    `)
//line zombiezen/queries.qtpl:139
	streamfillReqParams(qw422016, q)
//line zombiezen/queries.qtpl:139
	qw422016.N().S(`) (
    `)
//line zombiezen/queries.qtpl:141
	streamfillReturns(qw422016, q)
//line zombiezen/queries.qtpl:141
	qw422016.N().S(`) {
    ps := `)
//line zombiezen/queries.qtpl:143
	qw422016.E().S(q.Name.Pascal)
//line zombiezen/queries.qtpl:143
	qw422016.N().S(`(tx)

    return ps.Run(
`)
//line zombiezen/queries.qtpl:146
	if q.HasParams {
//line zombiezen/queries.qtpl:146
		qw422016.N().S(`        `)
//line zombiezen/queries.qtpl:147
		if q.ParamsIsSingularField {
//line zombiezen/queries.qtpl:147
			qw422016.N().S(`            `)
//line zombiezen/queries.qtpl:148
			qw422016.E().S(q.Params[0].Name.Camel)
//line zombiezen/queries.qtpl:148
			qw422016.N().S(`,
`)
//line zombiezen/queries.qtpl:149
		} else {
//line zombiezen/queries.qtpl:149
			qw422016.N().S(`            params,
`)
//line zombiezen/queries.qtpl:151
		}
//line zombiezen/queries.qtpl:152
	}
//line zombiezen/queries.qtpl:152
	qw422016.N().S(`
    )
}

`)
//line zombiezen/queries.qtpl:156
}

//line zombiezen/queries.qtpl:156
func WriteGenerateQuery(qq422016 qtio422016.Writer, q *GenerateQueryContext) {
//line zombiezen/queries.qtpl:156
	qw422016 := qt422016.AcquireWriter(qq422016)
//line zombiezen/queries.qtpl:156
	StreamGenerateQuery(qw422016, q)
//line zombiezen/queries.qtpl:156
	qt422016.ReleaseWriter(qw422016)
//line zombiezen/queries.qtpl:156
}

//line zombiezen/queries.qtpl:156
func GenerateQuery(q *GenerateQueryContext) string {
//line zombiezen/queries.qtpl:156
	qb422016 := qt422016.AcquireByteBuffer()
//line zombiezen/queries.qtpl:156
	WriteGenerateQuery(qb422016, q)
//line zombiezen/queries.qtpl:156
	qs422016 := string(qb422016.B)
//line zombiezen/queries.qtpl:156
	qt422016.ReleaseByteBuffer(qb422016)
//line zombiezen/queries.qtpl:156
	return qs422016
//line zombiezen/queries.qtpl:156
}

//line zombiezen/queries.qtpl:158
func streamfillResponse(qw422016 *qt422016.Writer, q *GenerateQueryContext) {
//line zombiezen/queries.qtpl:159
	if q.ResponseIsSingularField {
//line zombiezen/queries.qtpl:161
		f := q.ResponseFields[0]

//line zombiezen/queries.qtpl:163
		switch f.GoType.Original {
//line zombiezen/queries.qtpl:164
		case "time.Time":
//line zombiezen/queries.qtpl:164
			qw422016.N().S(`            toolbelt.JulianDayToTime(stmt.ColumnFloat(`)
//line zombiezen/queries.qtpl:165
			qw422016.N().D(f.Offset)
//line zombiezen/queries.qtpl:165
			qw422016.N().S(`))
`)
//line zombiezen/queries.qtpl:166
		case "time.Duration":
//line zombiezen/queries.qtpl:166
			qw422016.N().S(`            toolbelt.MillisecondsToDuration(stmt.ColumnInt64(`)
//line zombiezen/queries.qtpl:167
			qw422016.N().D(f.Offset)
//line zombiezen/queries.qtpl:167
			qw422016.N().S(`))
`)
//line zombiezen/queries.qtpl:168
		case "[]byte":
//line zombiezen/queries.qtpl:168
			qw422016.N().S(`            toolbelt.StmtBytesByCol(stmt, `)
//line zombiezen/queries.qtpl:169
			qw422016.N().D(f.Offset)
//line zombiezen/queries.qtpl:169
			qw422016.N().S(`),
`)
//line zombiezen/queries.qtpl:170
		default:
//line zombiezen/queries.qtpl:170
			qw422016.N().S(`            stmt.Column`)
//line zombiezen/queries.qtpl:171
			qw422016.E().S(f.SQLType.Pascal)
//line zombiezen/queries.qtpl:171
			qw422016.N().S(`(`)
//line zombiezen/queries.qtpl:171
			qw422016.N().D(f.Offset)
//line zombiezen/queries.qtpl:171
			qw422016.N().S(`)
`)
//line zombiezen/queries.qtpl:172
		}
//line zombiezen/queries.qtpl:173
	} else {
//line zombiezen/queries.qtpl:173
		qw422016.N().S(`    row := `)
//line zombiezen/queries.qtpl:174
		qw422016.E().S(q.Name.Pascal)
//line zombiezen/queries.qtpl:174
		qw422016.N().S(`Res{}
`)
//line zombiezen/queries.qtpl:175
		for _, f := range q.ResponseFields {
//line zombiezen/queries.qtpl:176
			if f.IsNullable {
//line zombiezen/queries.qtpl:176
				qw422016.N().S(`            isNull`)
//line zombiezen/queries.qtpl:177
				qw422016.E().S(f.Name.Pascal)
//line zombiezen/queries.qtpl:177
				qw422016.N().S(` := stmt.ColumnIsNull(`)
//line zombiezen/queries.qtpl:177
				qw422016.N().D(f.Offset)
//line zombiezen/queries.qtpl:177
				qw422016.N().S(`)
            if !isNull`)
//line zombiezen/queries.qtpl:178
				qw422016.E().S(f.Name.Pascal)
//line zombiezen/queries.qtpl:178
				qw422016.N().S(` {
                tmp := `)
//line zombiezen/queries.qtpl:179
				streamfillResponseField(qw422016, f)
//line zombiezen/queries.qtpl:179
				qw422016.N().S(`                row.`)
//line zombiezen/queries.qtpl:180
				qw422016.E().S(f.Name.Pascal)
//line zombiezen/queries.qtpl:180
				qw422016.N().S(` = &tmp
            }
`)
//line zombiezen/queries.qtpl:182
			} else {
//line zombiezen/queries.qtpl:182
				qw422016.N().S(`            row.`)
//line zombiezen/queries.qtpl:183
				qw422016.E().S(f.Name.Pascal)
//line zombiezen/queries.qtpl:183
				qw422016.N().S(` = `)
//line zombiezen/queries.qtpl:183
				streamfillResponseField(qw422016, f)
//line zombiezen/queries.qtpl:184
			}
//line zombiezen/queries.qtpl:185
		}
//line zombiezen/queries.qtpl:186
	}
//line zombiezen/queries.qtpl:187
}

//line zombiezen/queries.qtpl:187
func writefillResponse(qq422016 qtio422016.Writer, q *GenerateQueryContext) {
//line zombiezen/queries.qtpl:187
	qw422016 := qt422016.AcquireWriter(qq422016)
//line zombiezen/queries.qtpl:187
	streamfillResponse(qw422016, q)
//line zombiezen/queries.qtpl:187
	qt422016.ReleaseWriter(qw422016)
//line zombiezen/queries.qtpl:187
}

//line zombiezen/queries.qtpl:187
func fillResponse(q *GenerateQueryContext) string {
//line zombiezen/queries.qtpl:187
	qb422016 := qt422016.AcquireByteBuffer()
//line zombiezen/queries.qtpl:187
	writefillResponse(qb422016, q)
//line zombiezen/queries.qtpl:187
	qs422016 := string(qb422016.B)
//line zombiezen/queries.qtpl:187
	qt422016.ReleaseByteBuffer(qb422016)
//line zombiezen/queries.qtpl:187
	return qs422016
//line zombiezen/queries.qtpl:187
}

//line zombiezen/queries.qtpl:189
func streamfillResponseField(qw422016 *qt422016.Writer, f GenerateField) {
//line zombiezen/queries.qtpl:190
	switch f.GoType.Original {
//line zombiezen/queries.qtpl:191
	case "time.Time":
//line zombiezen/queries.qtpl:191
		qw422016.N().S(`        toolbelt.JulianDayToTime(stmt.ColumnFloat(`)
//line zombiezen/queries.qtpl:192
		qw422016.N().D(f.Offset)
//line zombiezen/queries.qtpl:192
		qw422016.N().S(`))
`)
//line zombiezen/queries.qtpl:193
	case "time.Duration":
//line zombiezen/queries.qtpl:193
		qw422016.N().S(`        toolbelt.MillisecondsToDuration(stmt.ColumnInt64(`)
//line zombiezen/queries.qtpl:194
		qw422016.N().D(f.Offset)
//line zombiezen/queries.qtpl:194
		qw422016.N().S(`))
`)
//line zombiezen/queries.qtpl:195
	case "[]byte":
//line zombiezen/queries.qtpl:195
		qw422016.N().S(`        toolbelt.StmtBytesByCol(stmt, `)
//line zombiezen/queries.qtpl:196
		qw422016.N().D(f.Offset)
//line zombiezen/queries.qtpl:196
		qw422016.N().S(`)
`)
//line zombiezen/queries.qtpl:197
	default:
//line zombiezen/queries.qtpl:197
		qw422016.N().S(`        stmt.Column`)
//line zombiezen/queries.qtpl:198
		qw422016.E().S(f.SQLType.Pascal)
//line zombiezen/queries.qtpl:198
		qw422016.N().S(`(`)
//line zombiezen/queries.qtpl:198
		qw422016.N().D(f.Offset)
//line zombiezen/queries.qtpl:198
		qw422016.N().S(`)
`)
//line zombiezen/queries.qtpl:199
	}
//line zombiezen/queries.qtpl:200
}

//line zombiezen/queries.qtpl:200
func writefillResponseField(qq422016 qtio422016.Writer, f GenerateField) {
//line zombiezen/queries.qtpl:200
	qw422016 := qt422016.AcquireWriter(qq422016)
//line zombiezen/queries.qtpl:200
	streamfillResponseField(qw422016, f)
//line zombiezen/queries.qtpl:200
	qt422016.ReleaseWriter(qw422016)
//line zombiezen/queries.qtpl:200
}

//line zombiezen/queries.qtpl:200
func fillResponseField(f GenerateField) string {
//line zombiezen/queries.qtpl:200
	qb422016 := qt422016.AcquireByteBuffer()
//line zombiezen/queries.qtpl:200
	writefillResponseField(qb422016, f)
//line zombiezen/queries.qtpl:200
	qs422016 := string(qb422016.B)
//line zombiezen/queries.qtpl:200
	qt422016.ReleaseByteBuffer(qb422016)
//line zombiezen/queries.qtpl:200
	return qs422016
//line zombiezen/queries.qtpl:200
}

//line zombiezen/queries.qtpl:202
func streamfillReqParams(qw422016 *qt422016.Writer, q *GenerateQueryContext) {
//line zombiezen/queries.qtpl:203
	if q.HasParams {
//line zombiezen/queries.qtpl:204
		if q.ParamsIsSingularField {
//line zombiezen/queries.qtpl:204
			qw422016.N().S(`        `)
//line zombiezen/queries.qtpl:205
			qw422016.E().S(q.Params[0].Name.Camel)
//line zombiezen/queries.qtpl:205
			qw422016.N().S(`  `)
//line zombiezen/queries.qtpl:205
			if q.Params[0].IsNullable {
//line zombiezen/queries.qtpl:205
				qw422016.N().S(`*`)
//line zombiezen/queries.qtpl:205
			}
//line zombiezen/queries.qtpl:205
			qw422016.E().S(q.Params[0].GoType.Original)
//line zombiezen/queries.qtpl:205
			qw422016.N().S(`,
`)
//line zombiezen/queries.qtpl:206
		} else {
//line zombiezen/queries.qtpl:206
			qw422016.N().S(`        params `)
//line zombiezen/queries.qtpl:207
			qw422016.E().S(q.Name.Pascal)
//line zombiezen/queries.qtpl:207
			qw422016.N().S(`Params,
`)
//line zombiezen/queries.qtpl:208
		}
//line zombiezen/queries.qtpl:209
	}
//line zombiezen/queries.qtpl:210
}

//line zombiezen/queries.qtpl:210
func writefillReqParams(qq422016 qtio422016.Writer, q *GenerateQueryContext) {
//line zombiezen/queries.qtpl:210
	qw422016 := qt422016.AcquireWriter(qq422016)
//line zombiezen/queries.qtpl:210
	streamfillReqParams(qw422016, q)
//line zombiezen/queries.qtpl:210
	qt422016.ReleaseWriter(qw422016)
//line zombiezen/queries.qtpl:210
}

//line zombiezen/queries.qtpl:210
func fillReqParams(q *GenerateQueryContext) string {
//line zombiezen/queries.qtpl:210
	qb422016 := qt422016.AcquireByteBuffer()
//line zombiezen/queries.qtpl:210
	writefillReqParams(qb422016, q)
//line zombiezen/queries.qtpl:210
	qs422016 := string(qb422016.B)
//line zombiezen/queries.qtpl:210
	qt422016.ReleaseByteBuffer(qb422016)
//line zombiezen/queries.qtpl:210
	return qs422016
//line zombiezen/queries.qtpl:210
}

//line zombiezen/queries.qtpl:213
func streamfillReturns(qw422016 *qt422016.Writer, q *GenerateQueryContext) {
//line zombiezen/queries.qtpl:214
	if q.HasResponse {
//line zombiezen/queries.qtpl:215
		if q.ResponseIsSingularField {
//line zombiezen/queries.qtpl:215
			qw422016.N().S(`        res `)
//line zombiezen/queries.qtpl:216
			if q.ResponseHasMultiple {
//line zombiezen/queries.qtpl:216
				qw422016.N().S(`[]`)
//line zombiezen/queries.qtpl:216
			}
//line zombiezen/queries.qtpl:216
			qw422016.E().S(q.ResponseFields[0].GoType.Original)
//line zombiezen/queries.qtpl:216
			qw422016.N().S(`,
`)
//line zombiezen/queries.qtpl:217
		} else {
//line zombiezen/queries.qtpl:217
			qw422016.N().S(`        res `)
//line zombiezen/queries.qtpl:218
			if q.ResponseHasMultiple {
//line zombiezen/queries.qtpl:218
				qw422016.N().S(`[]`)
//line zombiezen/queries.qtpl:218
			} else {
//line zombiezen/queries.qtpl:218
				qw422016.N().S(`*`)
//line zombiezen/queries.qtpl:218
			}
//line zombiezen/queries.qtpl:218
			qw422016.E().S(q.Name.Pascal)
//line zombiezen/queries.qtpl:218
			qw422016.N().S(`Res,
`)
//line zombiezen/queries.qtpl:219
		}
//line zombiezen/queries.qtpl:220
	}
//line zombiezen/queries.qtpl:220
	qw422016.N().S(`    err error,
`)
//line zombiezen/queries.qtpl:222
}

//line zombiezen/queries.qtpl:222
func writefillReturns(qq422016 qtio422016.Writer, q *GenerateQueryContext) {
//line zombiezen/queries.qtpl:222
	qw422016 := qt422016.AcquireWriter(qq422016)
//line zombiezen/queries.qtpl:222
	streamfillReturns(qw422016, q)
//line zombiezen/queries.qtpl:222
	qt422016.ReleaseWriter(qw422016)
//line zombiezen/queries.qtpl:222
}

//line zombiezen/queries.qtpl:222
func fillReturns(q *GenerateQueryContext) string {
//line zombiezen/queries.qtpl:222
	qb422016 := qt422016.AcquireByteBuffer()
//line zombiezen/queries.qtpl:222
	writefillReturns(qb422016, q)
//line zombiezen/queries.qtpl:222
	qs422016 := string(qb422016.B)
//line zombiezen/queries.qtpl:222
	qt422016.ReleaseByteBuffer(qb422016)
//line zombiezen/queries.qtpl:222
	return qs422016
//line zombiezen/queries.qtpl:222
}

//line zombiezen/queries.qtpl:224
func streamdeclareSlices(qw422016 *qt422016.Writer, q *GenerateQueryContext, isSingle bool) {
//line zombiezen/queries.qtpl:225
	for _, p := range q.Params {
//line zombiezen/queries.qtpl:226
		if p.IsSlice {
//line zombiezen/queries.qtpl:228
			accessor := p.Name.Camel
			if !isSingle {
				accessor = "params." + p.Name.Pascal
			}
			sliceVar := "slice" + p.Name.Pascal

//line zombiezen/queries.qtpl:233
			qw422016.N().S(`    `)
//line zombiezen/queries.qtpl:234
			qw422016.E().S(sliceVar)
//line zombiezen/queries.qtpl:234
			qw422016.N().S(` := `)
//line zombiezen/queries.qtpl:234
			qw422016.E().S(accessor)
//line zombiezen/queries.qtpl:234
			qw422016.N().S(`
    if len(`)
//line zombiezen/queries.qtpl:235
			qw422016.E().S(sliceVar)
//line zombiezen/queries.qtpl:235
			qw422016.N().S(`) > 0 {
        querySQL = strings.Replace(querySQL, "/*SLICE:`)
//line zombiezen/queries.qtpl:236
			qw422016.E().S(p.OriginalName)
//line zombiezen/queries.qtpl:236
			qw422016.N().S(`*/?", strings.Repeat(",?", len(`)
//line zombiezen/queries.qtpl:236
			qw422016.E().S(sliceVar)
//line zombiezen/queries.qtpl:236
			qw422016.N().S(`))[1:], 1)
    } else {
        querySQL = strings.Replace(querySQL, "/*SLICE:`)
//line zombiezen/queries.qtpl:238
			qw422016.E().S(p.OriginalName)
//line zombiezen/queries.qtpl:238
			qw422016.N().S(`*/?", "NULL", 1)
    }
`)
//line zombiezen/queries.qtpl:240
		}
//line zombiezen/queries.qtpl:241
	}
//line zombiezen/queries.qtpl:242
}

//line zombiezen/queries.qtpl:242
func writedeclareSlices(qq422016 qtio422016.Writer, q *GenerateQueryContext, isSingle bool) {
//line zombiezen/queries.qtpl:242
	qw422016 := qt422016.AcquireWriter(qq422016)
//line zombiezen/queries.qtpl:242
	streamdeclareSlices(qw422016, q, isSingle)
//line zombiezen/queries.qtpl:242
	qt422016.ReleaseWriter(qw422016)
//line zombiezen/queries.qtpl:242
}

//line zombiezen/queries.qtpl:242
func declareSlices(q *GenerateQueryContext, isSingle bool) string {
//line zombiezen/queries.qtpl:242
	qb422016 := qt422016.AcquireByteBuffer()
//line zombiezen/queries.qtpl:242
	writedeclareSlices(qb422016, q, isSingle)
//line zombiezen/queries.qtpl:242
	qs422016 := string(qb422016.B)
//line zombiezen/queries.qtpl:242
	qt422016.ReleaseByteBuffer(qb422016)
//line zombiezen/queries.qtpl:242
	return qs422016
//line zombiezen/queries.qtpl:242
}

//line zombiezen/queries.qtpl:244
func streambindParams(qw422016 *qt422016.Writer, q *GenerateQueryContext, isSingle bool) {
//line zombiezen/queries.qtpl:245
	for _, p := range q.Params {
//line zombiezen/queries.qtpl:246
		if p.IsSlice {
//line zombiezen/queries.qtpl:248
			sliceVar := "slice" + p.Name.Pascal

//line zombiezen/queries.qtpl:249
			qw422016.N().S(`    if len(`)
//line zombiezen/queries.qtpl:250
			qw422016.E().S(sliceVar)
//line zombiezen/queries.qtpl:250
			qw422016.N().S(`) > 0 {
        for _, elem := range `)
//line zombiezen/queries.qtpl:251
			qw422016.E().S(sliceVar)
//line zombiezen/queries.qtpl:251
			qw422016.N().S(` {
            `)
//line zombiezen/queries.qtpl:252
			streambindValueWithExpr(qw422016, p, "elem")
//line zombiezen/queries.qtpl:252
			qw422016.N().S(`
            bindIndex++
        }
    }
`)
//line zombiezen/queries.qtpl:256
		} else {
//line zombiezen/queries.qtpl:258
			accessor := p.Name.Camel
			if !isSingle {
				accessor = "params." + p.Name.Pascal
			}

//line zombiezen/queries.qtpl:263
			if p.IsNullable {
//line zombiezen/queries.qtpl:263
				qw422016.N().S(`    if `)
//line zombiezen/queries.qtpl:264
				qw422016.E().S(accessor)
//line zombiezen/queries.qtpl:264
				qw422016.N().S(` == nil {
        stmt.BindNull(bindIndex)
    } else {
        `)
//line zombiezen/queries.qtpl:267
				streambindValueWithExpr(qw422016, p, "*"+accessor)
//line zombiezen/queries.qtpl:267
				qw422016.N().S(`
    }
    bindIndex++
`)
//line zombiezen/queries.qtpl:270
			} else {
//line zombiezen/queries.qtpl:270
				qw422016.N().S(`    `)
//line zombiezen/queries.qtpl:271
				streambindValueWithExpr(qw422016, p, accessor)
//line zombiezen/queries.qtpl:271
				qw422016.N().S(`
    bindIndex++
`)
//line zombiezen/queries.qtpl:273
			}
//line zombiezen/queries.qtpl:274
		}
//line zombiezen/queries.qtpl:275
	}
//line zombiezen/queries.qtpl:276
}

//line zombiezen/queries.qtpl:276
func writebindParams(qq422016 qtio422016.Writer, q *GenerateQueryContext, isSingle bool) {
//line zombiezen/queries.qtpl:276
	qw422016 := qt422016.AcquireWriter(qq422016)
//line zombiezen/queries.qtpl:276
	streambindParams(qw422016, q, isSingle)
//line zombiezen/queries.qtpl:276
	qt422016.ReleaseWriter(qw422016)
//line zombiezen/queries.qtpl:276
}

//line zombiezen/queries.qtpl:276
func bindParams(q *GenerateQueryContext, isSingle bool) string {
//line zombiezen/queries.qtpl:276
	qb422016 := qt422016.AcquireByteBuffer()
//line zombiezen/queries.qtpl:276
	writebindParams(qb422016, q, isSingle)
//line zombiezen/queries.qtpl:276
	qs422016 := string(qb422016.B)
//line zombiezen/queries.qtpl:276
	qt422016.ReleaseByteBuffer(qb422016)
//line zombiezen/queries.qtpl:276
	return qs422016
//line zombiezen/queries.qtpl:276
}

//line zombiezen/queries.qtpl:278
func streambindValueWithExpr(qw422016 *qt422016.Writer, p GenerateField, value string) {
//line zombiezen/queries.qtpl:279
	switch p.BindGoType.Original {
//line zombiezen/queries.qtpl:280
	case "time.Time":
//line zombiezen/queries.qtpl:280
		qw422016.N().S(`        stmt.Bind`)
//line zombiezen/queries.qtpl:281
		qw422016.E().S(p.SQLType.Pascal)
//line zombiezen/queries.qtpl:281
		qw422016.N().S(`(bindIndex, toolbelt.TimeToJulianDay(`)
//line zombiezen/queries.qtpl:281
		qw422016.E().S(value)
//line zombiezen/queries.qtpl:281
		qw422016.N().S(`))
`)
//line zombiezen/queries.qtpl:282
	case "time.Duration":
//line zombiezen/queries.qtpl:282
		qw422016.N().S(`        stmt.Bind`)
//line zombiezen/queries.qtpl:283
		qw422016.E().S(p.SQLType.Pascal)
//line zombiezen/queries.qtpl:283
		qw422016.N().S(`(bindIndex, toolbelt.DurationToMilliseconds(`)
//line zombiezen/queries.qtpl:283
		qw422016.E().S(value)
//line zombiezen/queries.qtpl:283
		qw422016.N().S(`))
`)
//line zombiezen/queries.qtpl:284
	default:
//line zombiezen/queries.qtpl:284
		qw422016.N().S(`        stmt.Bind`)
//line zombiezen/queries.qtpl:285
		qw422016.E().S(p.SQLType.Pascal)
//line zombiezen/queries.qtpl:285
		qw422016.N().S(`(bindIndex, `)
//line zombiezen/queries.qtpl:285
		qw422016.E().S(value)
//line zombiezen/queries.qtpl:285
		qw422016.N().S(`)
`)
//line zombiezen/queries.qtpl:286
	}
//line zombiezen/queries.qtpl:287
}

//line zombiezen/queries.qtpl:287
func writebindValueWithExpr(qq422016 qtio422016.Writer, p GenerateField, value string) {
//line zombiezen/queries.qtpl:287
	qw422016 := qt422016.AcquireWriter(qq422016)
//line zombiezen/queries.qtpl:287
	streambindValueWithExpr(qw422016, p, value)
//line zombiezen/queries.qtpl:287
	qt422016.ReleaseWriter(qw422016)
//line zombiezen/queries.qtpl:287
}

//line zombiezen/queries.qtpl:287
func bindValueWithExpr(p GenerateField, value string) string {
//line zombiezen/queries.qtpl:287
	qb422016 := qt422016.AcquireByteBuffer()
//line zombiezen/queries.qtpl:287
	writebindValueWithExpr(qb422016, p, value)
//line zombiezen/queries.qtpl:287
	qs422016 := string(qb422016.B)
//line zombiezen/queries.qtpl:287
	qt422016.ReleaseByteBuffer(qb422016)
//line zombiezen/queries.qtpl:287
	return qs422016
//line zombiezen/queries.qtpl:287
}
