// Code generated by qtc from "queries.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:1
package zombiezen

//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:1
import "github.com/delaneyj/toolbelt"

//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:3
func StreamGenerateQuery(qw422016 *qt422016.Writer, q *GenerateQueryContext) {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:3
	qw422016.N().S(`
// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:6
	qw422016.E().S(q.PackageName.Lower)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:6
	qw422016.N().S(`

import (
    "fmt"
    "zombiezen.com/go/sqlite"

    `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:12
	if q.NeedsTimePackage {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:12
		qw422016.N().S(`
    "time"
    "github.com/delaneyj/toolbelt"
    `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:15
	}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:15
	qw422016.N().S(`
)

`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:18
	if q.HasResponse && !q.ResponseIsSingularField {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:18
		qw422016.N().S(`
type `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:19
		qw422016.E().S(q.Name.Pascal)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:19
		qw422016.N().S(`Res struct {
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:20
		for _, f := range q.ResponseFields {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:20
			qw422016.N().S(`        `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:21
			qw422016.E().S(f.Name.Pascal)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:21
			qw422016.N().S(` `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:21
			if f.IsNullable {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:21
				qw422016.N().S(`*`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:21
			}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:21
			qw422016.E().S(f.GoType.Original)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:21
			qw422016.N().S(` `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:21
			qw422016.N().S("`")
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:21
			qw422016.N().S(`json:"`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:21
			qw422016.E().S(f.Name.Lower)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:21
			qw422016.N().S(`"`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:21
			qw422016.N().S("`")
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:21
			qw422016.N().S(`
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:22
		}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:22
		qw422016.N().S(`}
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:24
	}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:24
	qw422016.N().S(`

`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:26
	if q.HasParams && !q.ParamsIsSingularField {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:26
		qw422016.N().S(`
type `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:27
		qw422016.E().S(q.Name.Pascal)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:27
		qw422016.N().S(`Params struct {
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:28
		for _, f := range q.Params {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:28
			qw422016.N().S(`        `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:29
			qw422016.E().S(f.Name.Pascal)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:29
			qw422016.N().S(` `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:29
			if f.IsNullable {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:29
				qw422016.N().S(`*`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:29
			}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:29
			qw422016.E().S(f.GoType.Original)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:29
			qw422016.N().S(` `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:29
			qw422016.N().S("`")
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:29
			qw422016.N().S(`json:"`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:29
			qw422016.E().S(f.Name.Lower)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:29
			qw422016.N().S(`"`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:29
			qw422016.N().S("`")
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:29
			qw422016.N().S(`
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:30
		}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:30
		qw422016.N().S(`}
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:32
	}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:32
	qw422016.N().S(`

type `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:34
	qw422016.E().S(q.Name.Pascal)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:34
	qw422016.N().S(`Stmt struct {
    stmt *sqlite.Stmt
}

func `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:38
	qw422016.E().S(q.Name.Pascal)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:38
	qw422016.N().S(`(tx *sqlite.Conn) *`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:38
	qw422016.E().S(q.Name.Pascal)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:38
	qw422016.N().S(`Stmt {
    // Prepare the statement into connection cache
    stmt := tx.Prep(`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:38
	qw422016.N().S("`")
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:38
	qw422016.N().S(`
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:41
	qw422016.N().S(q.SQL)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:41
	qw422016.N().S(`
    `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:41
	qw422016.N().S("`")
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:41
	qw422016.N().S(`)
    ps := &`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:43
	qw422016.E().S(q.Name.Pascal)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:43
	qw422016.N().S(`Stmt{stmt: stmt}
    return ps
}

func (ps *`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:47
	qw422016.E().S(q.Name.Pascal)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:47
	qw422016.N().S(`Stmt) Run(
    `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:48
	streamfillReqParams(qw422016, q)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:48
	qw422016.N().S(`) (
    `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:50
	streamfillReturns(qw422016, q)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:50
	qw422016.N().S(`) {
    defer ps.stmt.Reset()

`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:54
	if len(q.Params) > 0 {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:54
		qw422016.N().S(`    // Bind parameters
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:56
		for _, p := range q.Params {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:56
			qw422016.N().S(`        `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:57
			streamfillParams(qw422016, p.GoType, p.SQLType, p.Name, p.Column, q.ParamsIsSingularField, p.IsNullable)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:58
		}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:59
	}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:59
	qw422016.N().S(`
    // Execute the query
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:62
	if q.HasResponse {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:63
		if q.ResponseHasMultiple {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:63
			qw422016.N().S(`        for {
            if hasRow, err := ps.stmt.Step(); err != nil {
                return res, fmt.Errorf("failed to execute {{.Name.Lower}} SQL: %w", err)
            } else if !hasRow {
                break
            }

`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:71
			if q.ResponseIsSingularField {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:71
				qw422016.N().S(`            `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:72
				qw422016.E().S(q.ResponseFields[0].Name.Camel)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:72
				qw422016.N().S(` := `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:72
				streamfillResponse(qw422016, q)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:72
				qw422016.N().S(`            res = append(res, `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:73
				qw422016.E().S(q.ResponseFields[0].Name.Camel)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:73
				qw422016.N().S(`)
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:74
			} else {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:74
				qw422016.N().S(`            `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:75
				streamfillResponse(qw422016, q)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:75
				qw422016.N().S(`            res = append(res, row)
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:77
			}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:77
			qw422016.N().S(`        }
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:79
		} else {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:79
			qw422016.N().S(`        if hasRow, err := ps.stmt.Step(); err != nil {
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:81
			if q.ResponseIsSingularField {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:81
				qw422016.N().S(`            return res, fmt.Errorf("failed to execute {{.Name.Lower}} SQL: %w", err)
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:83
			} else {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:83
				qw422016.N().S(`            return res, fmt.Errorf("failed to execute {{.Name.Lower}} SQL: %w", err)
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:85
			}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:85
			qw422016.N().S(`        } else if hasRow {
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:87
			if q.ResponseIsSingularField {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:87
				qw422016.N().S(`            res = `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:88
				streamfillResponse(qw422016, q)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:89
			} else {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:89
				qw422016.N().S(`            `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:90
				streamfillResponse(qw422016, q)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:90
				qw422016.N().S(`            res = &row
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:92
			}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:92
			qw422016.N().S(`        }
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:94
		}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:95
	} else {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:95
		qw422016.N().S(`    if _, err := ps.stmt.Step(); err != nil {
        return fmt.Errorf("failed to execute `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:97
		qw422016.E().S(q.Name.Lower)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:97
		qw422016.N().S(` SQL: %w", err)
    }
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:99
	}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:99
	qw422016.N().S(`
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:101
	if q.HasResponse {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:101
		qw422016.N().S(`    return res, nil
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:103
	} else {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:103
		qw422016.N().S(`    return nil
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:105
	}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:105
	qw422016.N().S(`}

func Once`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:108
	qw422016.E().S(q.Name.Pascal)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:108
	qw422016.N().S(`(
    tx *sqlite.Conn,
    `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:110
	streamfillReqParams(qw422016, q)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:110
	qw422016.N().S(`) (
    `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:112
	streamfillReturns(qw422016, q)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:112
	qw422016.N().S(`) {
    ps := `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:114
	qw422016.E().S(q.Name.Pascal)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:114
	qw422016.N().S(`(tx)

    return ps.Run(
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:117
	if q.HasParams {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:117
		qw422016.N().S(`        `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:118
		if q.ParamsIsSingularField {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:118
			qw422016.N().S(`            `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:119
			qw422016.E().S(q.Params[0].Name.Camel)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:119
			qw422016.N().S(`,
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:120
		} else {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:120
			qw422016.N().S(`            params,
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:122
		}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:123
	}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:123
	qw422016.N().S(`
    )
}

`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:127
}

//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:127
func WriteGenerateQuery(qq422016 qtio422016.Writer, q *GenerateQueryContext) {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:127
	qw422016 := qt422016.AcquireWriter(qq422016)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:127
	StreamGenerateQuery(qw422016, q)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:127
	qt422016.ReleaseWriter(qw422016)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:127
}

//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:127
func GenerateQuery(q *GenerateQueryContext) string {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:127
	qb422016 := qt422016.AcquireByteBuffer()
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:127
	WriteGenerateQuery(qb422016, q)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:127
	qs422016 := string(qb422016.B)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:127
	qt422016.ReleaseByteBuffer(qb422016)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:127
	return qs422016
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:127
}

//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:129
func streamfillResponse(qw422016 *qt422016.Writer, q *GenerateQueryContext) {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:130
	if q.ResponseIsSingularField {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:132
		f := q.ResponseFields[0]

//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:134
		switch f.GoType.Original {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:135
		case "time.Time":
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:135
			qw422016.N().S(`            toolbelt.JulianDayToTime(ps.stmt.ColumnFloat(`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:136
			qw422016.N().D(f.Offset)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:136
			qw422016.N().S(`))
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:137
		case "time.Duration":
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:137
			qw422016.N().S(`            toolbelt.MillisecondsToDuration(ps.stmt.ColumnInt64(`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:138
			qw422016.N().D(f.Offset)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:138
			qw422016.N().S(`))
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:139
		case "[]byte":
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:139
			qw422016.N().S(`            toolbelt.StmtBytesByCol(ps.stmt, `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:140
			qw422016.N().D(f.Offset)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:140
			qw422016.N().S(`),
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:141
		default:
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:141
			qw422016.N().S(`            ps.stmt.Column`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:142
			qw422016.E().S(f.SQLType.Pascal)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:142
			qw422016.N().S(`(`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:142
			qw422016.N().D(f.Offset)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:142
			qw422016.N().S(`)
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:143
		}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:144
	} else {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:144
		qw422016.N().S(`    row := `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:145
		qw422016.E().S(q.Name.Pascal)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:145
		qw422016.N().S(`Res{}
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:146
		for _, f := range q.ResponseFields {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:147
			if f.IsNullable {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:147
				qw422016.N().S(`            isNull`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:148
				qw422016.E().S(f.Name.Pascal)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:148
				qw422016.N().S(` := ps.stmt.ColumnIsNull(`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:148
				qw422016.N().D(f.Offset)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:148
				qw422016.N().S(`)
            if !isNull`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:149
				qw422016.E().S(f.Name.Pascal)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:149
				qw422016.N().S(` {
                tmp := `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:150
				streamfillResponseField(qw422016, f)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:150
				qw422016.N().S(`                row.`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:151
				qw422016.E().S(f.Name.Pascal)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:151
				qw422016.N().S(` = &tmp
            }
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:153
			} else {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:153
				qw422016.N().S(`            row.`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:154
				qw422016.E().S(f.Name.Pascal)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:154
				qw422016.N().S(` = `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:154
				streamfillResponseField(qw422016, f)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:155
			}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:156
		}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:157
	}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:158
}

//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:158
func writefillResponse(qq422016 qtio422016.Writer, q *GenerateQueryContext) {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:158
	qw422016 := qt422016.AcquireWriter(qq422016)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:158
	streamfillResponse(qw422016, q)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:158
	qt422016.ReleaseWriter(qw422016)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:158
}

//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:158
func fillResponse(q *GenerateQueryContext) string {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:158
	qb422016 := qt422016.AcquireByteBuffer()
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:158
	writefillResponse(qb422016, q)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:158
	qs422016 := string(qb422016.B)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:158
	qt422016.ReleaseByteBuffer(qb422016)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:158
	return qs422016
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:158
}

//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:160
func streamfillResponseField(qw422016 *qt422016.Writer, f GenerateField) {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:161
	switch f.GoType.Original {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:162
	case "time.Time":
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:162
		qw422016.N().S(`        toolbelt.JulianDayToTime(ps.stmt.ColumnFloat(`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:163
		qw422016.N().D(f.Offset)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:163
		qw422016.N().S(`))
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:164
	case "time.Duration":
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:164
		qw422016.N().S(`        toolbelt.MillisecondsToDuration(ps.stmt.ColumnInt64(`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:165
		qw422016.N().D(f.Offset)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:165
		qw422016.N().S(`))
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:166
	case "[]byte":
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:166
		qw422016.N().S(`        toolbelt.StmtBytesByCol(ps.stmt, `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:167
		qw422016.N().D(f.Offset)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:167
		qw422016.N().S(`)
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:168
	default:
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:168
		qw422016.N().S(`        ps.stmt.Column`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:169
		qw422016.E().S(f.SQLType.Pascal)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:169
		qw422016.N().S(`(`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:169
		qw422016.N().D(f.Offset)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:169
		qw422016.N().S(`)
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:170
	}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:171
}

//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:171
func writefillResponseField(qq422016 qtio422016.Writer, f GenerateField) {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:171
	qw422016 := qt422016.AcquireWriter(qq422016)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:171
	streamfillResponseField(qw422016, f)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:171
	qt422016.ReleaseWriter(qw422016)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:171
}

//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:171
func fillResponseField(f GenerateField) string {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:171
	qb422016 := qt422016.AcquireByteBuffer()
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:171
	writefillResponseField(qb422016, f)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:171
	qs422016 := string(qb422016.B)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:171
	qt422016.ReleaseByteBuffer(qb422016)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:171
	return qs422016
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:171
}

//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:173
func streamfillReqParams(qw422016 *qt422016.Writer, q *GenerateQueryContext) {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:174
	if q.HasParams {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:175
		if q.ParamsIsSingularField {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:175
			qw422016.N().S(`        `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:176
			qw422016.E().S(q.Params[0].Name.Camel)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:176
			qw422016.N().S(`  `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:176
			if q.Params[0].IsNullable {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:176
				qw422016.N().S(`*`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:176
			}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:176
			qw422016.E().S(q.Params[0].GoType.Original)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:176
			qw422016.N().S(`,
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:177
		} else {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:177
			qw422016.N().S(`        params `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:178
			qw422016.E().S(q.Name.Pascal)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:178
			qw422016.N().S(`Params,
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:179
		}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:180
	}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:181
}

//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:181
func writefillReqParams(qq422016 qtio422016.Writer, q *GenerateQueryContext) {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:181
	qw422016 := qt422016.AcquireWriter(qq422016)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:181
	streamfillReqParams(qw422016, q)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:181
	qt422016.ReleaseWriter(qw422016)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:181
}

//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:181
func fillReqParams(q *GenerateQueryContext) string {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:181
	qb422016 := qt422016.AcquireByteBuffer()
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:181
	writefillReqParams(qb422016, q)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:181
	qs422016 := string(qb422016.B)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:181
	qt422016.ReleaseByteBuffer(qb422016)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:181
	return qs422016
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:181
}

//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:184
func streamfillReturns(qw422016 *qt422016.Writer, q *GenerateQueryContext) {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:185
	if q.HasResponse {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:186
		if q.ResponseIsSingularField {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:186
			qw422016.N().S(`        res `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:187
			if q.ResponseHasMultiple {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:187
				qw422016.N().S(`[]`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:187
			}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:187
			qw422016.E().S(q.ResponseFields[0].GoType.Original)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:187
			qw422016.N().S(`,
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:188
		} else {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:188
			qw422016.N().S(`        res `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:189
			if q.ResponseHasMultiple {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:189
				qw422016.N().S(`[]`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:189
			} else {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:189
				qw422016.N().S(`*`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:189
			}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:189
			qw422016.E().S(q.Name.Pascal)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:189
			qw422016.N().S(`Res,
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:190
		}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:191
	}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:191
	qw422016.N().S(`    err error,
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:193
}

//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:193
func writefillReturns(qq422016 qtio422016.Writer, q *GenerateQueryContext) {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:193
	qw422016 := qt422016.AcquireWriter(qq422016)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:193
	streamfillReturns(qw422016, q)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:193
	qt422016.ReleaseWriter(qw422016)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:193
}

//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:193
func fillReturns(q *GenerateQueryContext) string {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:193
	qb422016 := qt422016.AcquireByteBuffer()
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:193
	writefillReturns(qb422016, q)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:193
	qs422016 := string(qb422016.B)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:193
	qt422016.ReleaseByteBuffer(qb422016)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:193
	return qs422016
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:193
}

//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:195
func streamfillParams(qw422016 *qt422016.Writer, goType, sqlType, name toolbelt.CasedString, col int, isSingle, isNullable bool) {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:197
	pName := name.Camel
	if !isSingle {
		pName = "params." + name.Pascal
	}

//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:202
	if isNullable {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:202
		qw422016.N().S(`    if `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:203
		qw422016.E().S(pName)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:203
		qw422016.N().S(` == nil {
        ps.stmt.BindNull(`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:204
		qw422016.N().D(col)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:204
		qw422016.N().S(`)
    } else {
        `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:206
		streamfillParam(qw422016, goType, sqlType, col, "*"+pName)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:206
		qw422016.N().S(`    }
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:208
	} else {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:208
		qw422016.N().S(`    `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:209
		streamfillParam(qw422016, goType, sqlType, col, pName)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:210
	}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:211
}

//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:211
func writefillParams(qq422016 qtio422016.Writer, goType, sqlType, name toolbelt.CasedString, col int, isSingle, isNullable bool) {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:211
	qw422016 := qt422016.AcquireWriter(qq422016)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:211
	streamfillParams(qw422016, goType, sqlType, name, col, isSingle, isNullable)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:211
	qt422016.ReleaseWriter(qw422016)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:211
}

//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:211
func fillParams(goType, sqlType, name toolbelt.CasedString, col int, isSingle, isNullable bool) string {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:211
	qb422016 := qt422016.AcquireByteBuffer()
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:211
	writefillParams(qb422016, goType, sqlType, name, col, isSingle, isNullable)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:211
	qs422016 := string(qb422016.B)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:211
	qt422016.ReleaseByteBuffer(qb422016)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:211
	return qs422016
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:211
}

//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:213
func streamfillParam(qw422016 *qt422016.Writer, goType, sqlType toolbelt.CasedString, col int, pName string) {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:214
	switch goType.Original {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:215
	case "time.Time":
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:215
		qw422016.N().S(`        ps.stmt.Bind`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:216
		qw422016.E().S(sqlType.Pascal)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:216
		qw422016.N().S(`(`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:216
		qw422016.N().D(col)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:216
		qw422016.N().S(`, toolbelt.TimeToJulianDay(`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:216
		qw422016.E().S(pName)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:216
		qw422016.N().S(`))
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:217
	case "time.Duration":
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:217
		qw422016.N().S(`        ps.stmt.Bind`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:218
		qw422016.E().S(sqlType.Pascal)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:218
		qw422016.N().S(`(`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:218
		qw422016.N().D(col)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:218
		qw422016.N().S(`, toolbelt.DurationToMilliseconds(`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:218
		qw422016.E().S(pName)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:218
		qw422016.N().S(`))
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:219
	default:
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:219
		qw422016.N().S(`        ps.stmt.Bind`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:220
		qw422016.E().S(sqlType.Pascal)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:220
		qw422016.N().S(`(`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:220
		qw422016.N().D(col)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:220
		qw422016.N().S(`, `)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:220
		qw422016.E().S(pName)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:220
		qw422016.N().S(`)
`)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:221
	}
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:222
}

//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:222
func writefillParam(qq422016 qtio422016.Writer, goType, sqlType toolbelt.CasedString, col int, pName string) {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:222
	qw422016 := qt422016.AcquireWriter(qq422016)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:222
	streamfillParam(qw422016, goType, sqlType, col, pName)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:222
	qt422016.ReleaseWriter(qw422016)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:222
}

//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:222
func fillParam(goType, sqlType toolbelt.CasedString, col int, pName string) string {
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:222
	qb422016 := qt422016.AcquireByteBuffer()
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:222
	writefillParam(qb422016, goType, sqlType, col, pName)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:222
	qs422016 := string(qb422016.B)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:222
	qt422016.ReleaseByteBuffer(qb422016)
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:222
	return qs422016
//line sqlc-gen-zombiezen/zombiezen/queries.qtpl:222
}
