// Code generated by qtc from "util.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line sqlc-gen-zombiezen/zombiezen/util.qtpl:1
package zombiezen

//line sqlc-gen-zombiezen/zombiezen/util.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line sqlc-gen-zombiezen/zombiezen/util.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line sqlc-gen-zombiezen/zombiezen/util.qtpl:1
func StreamGenerateUtil(qw422016 *qt422016.Writer, t *GenerateUtilContext) {
//line sqlc-gen-zombiezen/zombiezen/util.qtpl:1
	qw422016.N().S(`
// Code generated by "sqlc-gen-zombiezen". DO NOT EDIT.

package `)
//line sqlc-gen-zombiezen/zombiezen/util.qtpl:4
	qw422016.E().S(t.PackageName.Lower)
//line sqlc-gen-zombiezen/zombiezen/util.qtpl:4
	qw422016.N().S(`

import (
    "time"

    "zombiezen.com/go/sqlite"
)

const (
	secondsInADay      = 86400
	UnixEpochJulianDay = 2440587.5
)

// TimeToJulianDay converts a time.Time into a Julian day.
func TimeToJulianDay(t time.Time) float64 {
	return float64(t.UTC().Unix())/secondsInADay + UnixEpochJulianDay
}

// JulianDayToTime converts a Julian day into a time.Time.
func JulianDayToTime(d float64) time.Time {
	return time.Unix(int64((d-UnixEpochJulianDay)*secondsInADay), 0).UTC()
}

func MillisecondsToDuration(ms int64) time.Duration {
	return time.Duration(ms) * time.Millisecond
}

func DurationToMilliseconds(d time.Duration) int64 {
	return int64(d / time.Millisecond)
}

func StmtBytesByCol(stmt *sqlite.Stmt, col int) []byte {
	bl := stmt.ColumnLen(col)
	if bl == 0 {
		return nil
	}

	buf := make([]byte, bl)
	if writtent := stmt.ColumnBytes(col, buf); writtent != bl {
		return nil
	}

	return buf
}
`)
//line sqlc-gen-zombiezen/zombiezen/util.qtpl:48
}

//line sqlc-gen-zombiezen/zombiezen/util.qtpl:48
func WriteGenerateUtil(qq422016 qtio422016.Writer, t *GenerateUtilContext) {
//line sqlc-gen-zombiezen/zombiezen/util.qtpl:48
	qw422016 := qt422016.AcquireWriter(qq422016)
//line sqlc-gen-zombiezen/zombiezen/util.qtpl:48
	StreamGenerateUtil(qw422016, t)
//line sqlc-gen-zombiezen/zombiezen/util.qtpl:48
	qt422016.ReleaseWriter(qw422016)
//line sqlc-gen-zombiezen/zombiezen/util.qtpl:48
}

//line sqlc-gen-zombiezen/zombiezen/util.qtpl:48
func GenerateUtil(t *GenerateUtilContext) string {
//line sqlc-gen-zombiezen/zombiezen/util.qtpl:48
	qb422016 := qt422016.AcquireByteBuffer()
//line sqlc-gen-zombiezen/zombiezen/util.qtpl:48
	WriteGenerateUtil(qb422016, t)
//line sqlc-gen-zombiezen/zombiezen/util.qtpl:48
	qs422016 := string(qb422016.B)
//line sqlc-gen-zombiezen/zombiezen/util.qtpl:48
	qt422016.ReleaseByteBuffer(qb422016)
//line sqlc-gen-zombiezen/zombiezen/util.qtpl:48
	return qs422016
//line sqlc-gen-zombiezen/zombiezen/util.qtpl:48
}
