// Code generated by qtc from "services_server_go.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line services_server_go.qtpl:1
package natsrpc

//line services_server_go.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line services_server_go.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line services_server_go.qtpl:1
func streamgoServerTemplate(qw422016 *qt422016.Writer, pkg *packageTmplData) {
//line services_server_go.qtpl:1
	qw422016.N().S(`
// Code generated by protoc-gen-go-natsrpc. DO NOT EDIT.

package `)
//line services_server_go.qtpl:4
	qw422016.E().S(pkg.PackageName.Snake)
//line services_server_go.qtpl:4
	qw422016.N().S(`

import (
    "context"
    "errors"
    "fmt"
    "log"

    "github.com/nats-io/nats.go"
    "google.golang.org/protobuf/proto"
    "gopkg.in/typ.v4/sync2"
)

`)
//line services_server_go.qtpl:17
	for _, service := range pkg.Services {
//line services_server_go.qtpl:19
		nsp := service.Name.Pascal

//line services_server_go.qtpl:20
		qw422016.N().S(`
type `)
//line services_server_go.qtpl:22
		qw422016.E().S(nsp)
//line services_server_go.qtpl:22
		qw422016.N().S(`Service interface {
    OnClose() error

    //#region Methods!
`)
//line services_server_go.qtpl:26
		for _, method := range service.Methods {
//line services_server_go.qtpl:28
			cs := method.IsClientStreaming
			ss := method.IsServerStreaming

//line services_server_go.qtpl:31
			switch {
//line services_server_go.qtpl:32
			case !cs && !ss:
//line services_server_go.qtpl:32
				qw422016.N().S(`			`)
//line services_server_go.qtpl:33
				qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:33
				qw422016.N().S(`(ctx context.Context, req *`)
//line services_server_go.qtpl:33
				qw422016.E().S(method.InputType.Original)
//line services_server_go.qtpl:33
				qw422016.N().S(`) (res *`)
//line services_server_go.qtpl:33
				qw422016.E().S(method.OutputType.Original)
//line services_server_go.qtpl:33
				qw422016.N().S(`, err error) // Unary call for `)
//line services_server_go.qtpl:33
				qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:33
				qw422016.N().S(`
`)
//line services_server_go.qtpl:34
			case cs && !ss:
//line services_server_go.qtpl:34
				qw422016.N().S(`            `)
//line services_server_go.qtpl:35
				qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:35
				qw422016.N().S(`(ctx context.Context, reqCh <-chan *`)
//line services_server_go.qtpl:35
				qw422016.E().S(method.InputType.Original)
//line services_server_go.qtpl:35
				qw422016.N().S(`) (res *`)
//line services_server_go.qtpl:35
				qw422016.E().S(method.OutputType.Original)
//line services_server_go.qtpl:35
				qw422016.N().S(`, err error) // Client streaming call for `)
//line services_server_go.qtpl:35
				qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:35
				qw422016.N().S(`
`)
//line services_server_go.qtpl:36
			case !cs && ss:
//line services_server_go.qtpl:36
				qw422016.N().S(`			`)
//line services_server_go.qtpl:37
				qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:37
				qw422016.N().S(`(ctx context.Context, req *`)
//line services_server_go.qtpl:37
				qw422016.E().S(method.InputType.Original)
//line services_server_go.qtpl:37
				qw422016.N().S(`, resCh chan<- *`)
//line services_server_go.qtpl:37
				qw422016.E().S(method.OutputType.Original)
//line services_server_go.qtpl:37
				qw422016.N().S(`) (err  error) // Server streaming call for `)
//line services_server_go.qtpl:37
				qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:37
				qw422016.N().S(`
`)
//line services_server_go.qtpl:38
			case cs && ss:
//line services_server_go.qtpl:38
				qw422016.N().S(`			`)
//line services_server_go.qtpl:39
				qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:39
				qw422016.N().S(`(ctx context.Context, reqCh <-chan *`)
//line services_server_go.qtpl:39
				qw422016.E().S(method.InputType.Original)
//line services_server_go.qtpl:39
				qw422016.N().S(`, resCh chan<- *`)
//line services_server_go.qtpl:39
				qw422016.E().S(method.OutputType.Original)
//line services_server_go.qtpl:39
				qw422016.N().S(`, errCh chan<- error) error // Bidirectional streaming call for `)
//line services_server_go.qtpl:39
				qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:39
				qw422016.N().S(`
`)
//line services_server_go.qtpl:40
			}
//line services_server_go.qtpl:41
		}
//line services_server_go.qtpl:41
		qw422016.N().S(`    //#endregion
}

const `)
//line services_server_go.qtpl:45
		qw422016.E().S(nsp)
//line services_server_go.qtpl:45
		qw422016.N().S(`ServiceSubject = "`)
//line services_server_go.qtpl:45
		qw422016.E().S(service.Subject)
//line services_server_go.qtpl:45
		qw422016.N().S(`"

type `)
//line services_server_go.qtpl:47
		qw422016.E().S(nsp)
//line services_server_go.qtpl:47
		qw422016.N().S(`ServiceRunner struct {
    baseSubject string
    service `)
//line services_server_go.qtpl:49
		qw422016.E().S(nsp)
//line services_server_go.qtpl:49
		qw422016.N().S(`Service
    nc *nats.Conn
	subs []*nats.Subscription
}

func New`)
//line services_server_go.qtpl:54
		qw422016.E().S(nsp)
//line services_server_go.qtpl:54
		qw422016.N().S(`ServiceRunnerSingleton(ctx context.Context, nc *nats.Conn, service `)
//line services_server_go.qtpl:54
		qw422016.E().S(nsp)
//line services_server_go.qtpl:54
		qw422016.N().S(`Service) (*`)
//line services_server_go.qtpl:54
		qw422016.E().S(nsp)
//line services_server_go.qtpl:54
		qw422016.N().S(`ServiceRunner, error) {
	return New`)
//line services_server_go.qtpl:55
		qw422016.E().S(nsp)
//line services_server_go.qtpl:55
		qw422016.N().S(`ServiceRunner(ctx, nc, service, 0)
}

func New`)
//line services_server_go.qtpl:58
		qw422016.E().S(nsp)
//line services_server_go.qtpl:58
		qw422016.N().S(`ServiceRunner(ctx context.Context, nc *nats.Conn, service `)
//line services_server_go.qtpl:58
		qw422016.E().S(nsp)
//line services_server_go.qtpl:58
		qw422016.N().S(`Service, instanceID int64) (*`)
//line services_server_go.qtpl:58
		qw422016.E().S(nsp)
//line services_server_go.qtpl:58
		qw422016.N().S(`ServiceRunner, error) {
	subjectSuffix := ""
	if instanceID > 0 {
		subjectSuffix = fmt.Sprintf(".%d", instanceID)
	}

	baseSubject := fmt.Sprintf("`)
//line services_server_go.qtpl:64
		qw422016.E().S(service.Subject)
//line services_server_go.qtpl:64
		qw422016.N().S(`%s", subjectSuffix)
`)
//line services_server_go.qtpl:65
		for _, method := range service.Methods {
//line services_server_go.qtpl:65
			qw422016.N().S(`       `)
//line services_server_go.qtpl:66
			qw422016.E().S(method.Name.Camel)
//line services_server_go.qtpl:66
			qw422016.N().S(`Subject := baseSubject + ".`)
//line services_server_go.qtpl:66
			qw422016.E().S(method.Name.Kebab)
//line services_server_go.qtpl:66
			qw422016.N().S(`"
`)
//line services_server_go.qtpl:67
		}
//line services_server_go.qtpl:67
		qw422016.N().S(`
    runner := &`)
//line services_server_go.qtpl:69
		qw422016.E().S(nsp)
//line services_server_go.qtpl:69
		qw422016.N().S(`ServiceRunner{
        service: service,
        nc: nc,
    }

	`)
//line services_server_go.qtpl:74
		if len(service.Methods) > 0 {
//line services_server_go.qtpl:74
			qw422016.N().S(`
		var (
			sub *nats.Subscription
			err error
		)
`)
//line services_server_go.qtpl:79
			for _, method := range service.Methods {
//line services_server_go.qtpl:81
				subjectName := method.Name.Camel + "Subject"
				ss, cs := method.IsServerStreaming, method.IsClientStreaming

//line services_server_go.qtpl:84
				switch {
//line services_server_go.qtpl:85
				case !cs && !ss:
//line services_server_go.qtpl:85
					qw422016.N().S(`            `)
//line services_server_go.qtpl:86
					streamgoServerUnaryHandler(qw422016, subjectName, method)
//line services_server_go.qtpl:86
					qw422016.N().S(`
`)
//line services_server_go.qtpl:87
				case cs && !ss:
//line services_server_go.qtpl:87
					qw422016.N().S(`			`)
//line services_server_go.qtpl:88
					streamgoServerClientStreamHandler(qw422016, subjectName, method)
//line services_server_go.qtpl:88
					qw422016.N().S(`
`)
//line services_server_go.qtpl:89
				case !cs && ss:
//line services_server_go.qtpl:89
					qw422016.N().S(`            `)
//line services_server_go.qtpl:90
					streamgoServerServerStreamHandler(qw422016, subjectName, method)
//line services_server_go.qtpl:90
					qw422016.N().S(`
`)
//line services_server_go.qtpl:91
				case cs && ss:
//line services_server_go.qtpl:91
					qw422016.N().S(`			`)
//line services_server_go.qtpl:92
					streamgoServerBidiStreamHandler(qw422016, subjectName, method)
//line services_server_go.qtpl:92
					qw422016.N().S(`
`)
//line services_server_go.qtpl:93
				}
//line services_server_go.qtpl:93
				qw422016.N().S(`		if err != nil {
			return nil, fmt.Errorf("failed to subscribe to `)
//line services_server_go.qtpl:95
				qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:95
				qw422016.N().S(`: %w", err)
		}
		runner.subs = append(runner.subs, sub)
`)
//line services_server_go.qtpl:98
			}
//line services_server_go.qtpl:98
			qw422016.N().S(`	`)
//line services_server_go.qtpl:99
		}
//line services_server_go.qtpl:99
		qw422016.N().S(`

    return runner,nil
}

func (runner *`)
//line services_server_go.qtpl:104
		qw422016.E().S(nsp)
//line services_server_go.qtpl:104
		qw422016.N().S(`ServiceRunner) Close() error {
    var errs []error

	for _, sub := range runner.subs {
		if err := sub.Unsubscribe(); err != nil {
			errs = append(errs, err)
		}
	}

    if runner.service != nil {
        if err := runner.service.OnClose(); err != nil {
            errs = append(errs, err)
        }
    }

    if err := errors.Join(errs...); err != nil {
        return fmt.Errorf("failed to close runner: %w", err)
    }

    return nil
}

`)
//line services_server_go.qtpl:126
	}
//line services_server_go.qtpl:126
	qw422016.N().S(`
`)
//line services_server_go.qtpl:128
}

//line services_server_go.qtpl:128
func writegoServerTemplate(qq422016 qtio422016.Writer, pkg *packageTmplData) {
//line services_server_go.qtpl:128
	qw422016 := qt422016.AcquireWriter(qq422016)
//line services_server_go.qtpl:128
	streamgoServerTemplate(qw422016, pkg)
//line services_server_go.qtpl:128
	qt422016.ReleaseWriter(qw422016)
//line services_server_go.qtpl:128
}

//line services_server_go.qtpl:128
func goServerTemplate(pkg *packageTmplData) string {
//line services_server_go.qtpl:128
	qb422016 := qt422016.AcquireByteBuffer()
//line services_server_go.qtpl:128
	writegoServerTemplate(qb422016, pkg)
//line services_server_go.qtpl:128
	qs422016 := string(qb422016.B)
//line services_server_go.qtpl:128
	qt422016.ReleaseByteBuffer(qb422016)
//line services_server_go.qtpl:128
	return qs422016
//line services_server_go.qtpl:128
}

//line services_server_go.qtpl:131
func streamgoServerUnaryHandler(qw422016 *qt422016.Writer, subjectName string, method *methodTmplData) {
//line services_server_go.qtpl:131
	qw422016.N().S(`
// Unary call for `)
//line services_server_go.qtpl:132
	qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:132
	qw422016.N().S(`
sub, err = nc.Subscribe(`)
//line services_server_go.qtpl:133
	qw422016.E().S(subjectName)
//line services_server_go.qtpl:133
	qw422016.N().S(`, func(msg *nats.Msg) {
        req := &`)
//line services_server_go.qtpl:134
	qw422016.E().S(method.InputType.Original)
//line services_server_go.qtpl:134
	qw422016.N().S(`{}
		if err := proto.Unmarshal(msg.Data, req); err != nil {
			sendError(msg, fmt.Errorf("failed to unmarshal request: %w", err))
			return
		}

		res, err := runner.service.`)
//line services_server_go.qtpl:140
	qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:140
	qw422016.N().S(`(context.Background(),req)
		if err != nil {
			sendError(msg, err)
			return
		}
		sendSuccess(msg, res)
	})
`)
//line services_server_go.qtpl:147
}

//line services_server_go.qtpl:147
func writegoServerUnaryHandler(qq422016 qtio422016.Writer, subjectName string, method *methodTmplData) {
//line services_server_go.qtpl:147
	qw422016 := qt422016.AcquireWriter(qq422016)
//line services_server_go.qtpl:147
	streamgoServerUnaryHandler(qw422016, subjectName, method)
//line services_server_go.qtpl:147
	qt422016.ReleaseWriter(qw422016)
//line services_server_go.qtpl:147
}

//line services_server_go.qtpl:147
func goServerUnaryHandler(subjectName string, method *methodTmplData) string {
//line services_server_go.qtpl:147
	qb422016 := qt422016.AcquireByteBuffer()
//line services_server_go.qtpl:147
	writegoServerUnaryHandler(qb422016, subjectName, method)
//line services_server_go.qtpl:147
	qs422016 := string(qb422016.B)
//line services_server_go.qtpl:147
	qt422016.ReleaseByteBuffer(qb422016)
//line services_server_go.qtpl:147
	return qs422016
//line services_server_go.qtpl:147
}

//line services_server_go.qtpl:149
func streamgoServerClientStreamHandler(qw422016 *qt422016.Writer, subjectName string, method *methodTmplData) {
//line services_server_go.qtpl:149
	qw422016.N().S(`
`)
//line services_server_go.qtpl:151
	reqChName := method.Name.Camel + "ClientReqChs"
	inputName := method.InputType.Original

//line services_server_go.qtpl:153
	qw422016.N().S(`
// Client streaming call for `)
//line services_server_go.qtpl:154
	qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:154
	qw422016.N().S(`
`)
//line services_server_go.qtpl:155
	qw422016.E().S(reqChName)
//line services_server_go.qtpl:155
	qw422016.N().S(` := sync2.Map[string, chan *`)
//line services_server_go.qtpl:155
	qw422016.N().S(inputName)
//line services_server_go.qtpl:155
	qw422016.N().S(`]{}
sub, err = nc.Subscribe(`)
//line services_server_go.qtpl:156
	qw422016.E().S(subjectName)
//line services_server_go.qtpl:156
	qw422016.N().S(`, func(msg *nats.Msg) {
		// Check for end of stream
		if len(msg.Data) == 0 {
			log.Printf("Got EOF")
			reqCh, ok := `)
//line services_server_go.qtpl:160
	qw422016.E().S(reqChName)
//line services_server_go.qtpl:160
	qw422016.N().S(`.Load(msg.Reply)
			if !ok {
				sendError(msg, errors.New("no request channel found"))
				return
			}
			close(reqCh)
			`)
//line services_server_go.qtpl:166
	qw422016.E().S(reqChName)
//line services_server_go.qtpl:166
	qw422016.N().S(`.Delete(msg.Reply)
			return
		}

		// Check for request
		req := &`)
//line services_server_go.qtpl:171
	qw422016.N().S(inputName)
//line services_server_go.qtpl:171
	qw422016.N().S(`{}
		if err := proto.Unmarshal(msg.Data, req); err != nil {
			sendError(msg, fmt.Errorf("failed to unmarshal request: %w", err))
			return
		}

		log.Printf("Got request: %v", req)

		// Check for request channel
		reqCh, ok := `)
//line services_server_go.qtpl:180
	qw422016.E().S(reqChName)
//line services_server_go.qtpl:180
	qw422016.N().S(`.Load(msg.Reply)
		if !ok {
			reqCh = make(chan *`)
//line services_server_go.qtpl:182
	qw422016.N().S(inputName)
//line services_server_go.qtpl:182
	qw422016.N().S(`)

			`)
//line services_server_go.qtpl:184
	qw422016.E().S(reqChName)
//line services_server_go.qtpl:184
	qw422016.N().S(`.Store(msg.Reply, reqCh)

			go func() {
				res, err := runner.service.`)
//line services_server_go.qtpl:187
	qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:187
	qw422016.N().S(`(context.Background(),reqCh)
				if err != nil {
					sendError(msg, err)
					return
				}
				sendSuccess(msg, res)
			}()
		}
		reqCh <- req
	})
`)
//line services_server_go.qtpl:197
}

//line services_server_go.qtpl:197
func writegoServerClientStreamHandler(qq422016 qtio422016.Writer, subjectName string, method *methodTmplData) {
//line services_server_go.qtpl:197
	qw422016 := qt422016.AcquireWriter(qq422016)
//line services_server_go.qtpl:197
	streamgoServerClientStreamHandler(qw422016, subjectName, method)
//line services_server_go.qtpl:197
	qt422016.ReleaseWriter(qw422016)
//line services_server_go.qtpl:197
}

//line services_server_go.qtpl:197
func goServerClientStreamHandler(subjectName string, method *methodTmplData) string {
//line services_server_go.qtpl:197
	qb422016 := qt422016.AcquireByteBuffer()
//line services_server_go.qtpl:197
	writegoServerClientStreamHandler(qb422016, subjectName, method)
//line services_server_go.qtpl:197
	qs422016 := string(qb422016.B)
//line services_server_go.qtpl:197
	qt422016.ReleaseByteBuffer(qb422016)
//line services_server_go.qtpl:197
	return qs422016
//line services_server_go.qtpl:197
}

//line services_server_go.qtpl:199
func streamgoServerServerStreamHandler(qw422016 *qt422016.Writer, subjectName string, method *methodTmplData) {
//line services_server_go.qtpl:199
	qw422016.N().S(`
// Server streaming call for `)
//line services_server_go.qtpl:200
	qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:200
	qw422016.N().S(`
sub, err = nc.Subscribe(`)
//line services_server_go.qtpl:201
	qw422016.E().S(subjectName)
//line services_server_go.qtpl:201
	qw422016.N().S(`, func(msg *nats.Msg) {
    req := &`)
//line services_server_go.qtpl:202
	qw422016.E().S(method.InputType.Original)
//line services_server_go.qtpl:202
	qw422016.N().S(`{}
    if err := proto.Unmarshal(msg.Data, req); err != nil {
        sendError(msg, fmt.Errorf("failed to unmarshal request: %w", err))
        return
    }

	go func() {
		resCh := make(chan *`)
//line services_server_go.qtpl:209
	qw422016.E().S(method.OutputType.Original)
//line services_server_go.qtpl:209
	qw422016.N().S(`)
		defer close(resCh)

		// Send responses to client
		go func () {
			defer sendEOF(msg)
			for {
				select {
				case res, ok := <-resCh:
					if !ok {
						return
					}
					sendSuccess(msg, res)
				}
			}
		}()

		// User defined handler, this will block until the context is done
		if err := runner.service.`)
//line services_server_go.qtpl:227
	qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:227
	qw422016.N().S(`(ctx, req, resCh); err != nil {
			sendError(msg, err)
		}
	}()
})
`)
//line services_server_go.qtpl:232
}

//line services_server_go.qtpl:232
func writegoServerServerStreamHandler(qq422016 qtio422016.Writer, subjectName string, method *methodTmplData) {
//line services_server_go.qtpl:232
	qw422016 := qt422016.AcquireWriter(qq422016)
//line services_server_go.qtpl:232
	streamgoServerServerStreamHandler(qw422016, subjectName, method)
//line services_server_go.qtpl:232
	qt422016.ReleaseWriter(qw422016)
//line services_server_go.qtpl:232
}

//line services_server_go.qtpl:232
func goServerServerStreamHandler(subjectName string, method *methodTmplData) string {
//line services_server_go.qtpl:232
	qb422016 := qt422016.AcquireByteBuffer()
//line services_server_go.qtpl:232
	writegoServerServerStreamHandler(qb422016, subjectName, method)
//line services_server_go.qtpl:232
	qs422016 := string(qb422016.B)
//line services_server_go.qtpl:232
	qt422016.ReleaseByteBuffer(qb422016)
//line services_server_go.qtpl:232
	return qs422016
//line services_server_go.qtpl:232
}

//line services_server_go.qtpl:234
func streamgoServerBidiStreamHandler(qw422016 *qt422016.Writer, subjectName string, method *methodTmplData) {
//line services_server_go.qtpl:234
	qw422016.N().S(`
`)
//line services_server_go.qtpl:236
	reqChName := method.Name.Camel + "BiReqChs"
	inputName := method.InputType.Original

//line services_server_go.qtpl:238
	qw422016.N().S(`
// Bidirectional streaming call for `)
//line services_server_go.qtpl:239
	qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:239
	qw422016.N().S(`
`)
//line services_server_go.qtpl:240
	qw422016.E().S(reqChName)
//line services_server_go.qtpl:240
	qw422016.N().S(` := sync2.Map[string, chan *`)
//line services_server_go.qtpl:240
	qw422016.N().S(inputName)
//line services_server_go.qtpl:240
	qw422016.N().S(`]{}
sub, err = nc.Subscribe(`)
//line services_server_go.qtpl:241
	qw422016.E().S(subjectName)
//line services_server_go.qtpl:241
	qw422016.N().S(`, func(msg *nats.Msg) {
		// Check for end of stream
		if len(msg.Data) == 0 {
			reqCh, ok := `)
//line services_server_go.qtpl:244
	qw422016.E().S(reqChName)
//line services_server_go.qtpl:244
	qw422016.N().S(`.Load(msg.Reply)
			if !ok {
				sendError(msg, errors.New("no request channel found"))
				return
			}
			close(reqCh)
			`)
//line services_server_go.qtpl:250
	qw422016.E().S(reqChName)
//line services_server_go.qtpl:250
	qw422016.N().S(`.Delete(msg.Reply)
			return
		}

		// Check for request
		req := &`)
//line services_server_go.qtpl:255
	qw422016.N().S(inputName)
//line services_server_go.qtpl:255
	qw422016.N().S(`{}
		if err := proto.Unmarshal(msg.Data, req); err != nil {
			sendError(msg, fmt.Errorf("failed to unmarshal request: %w", err))
			return
		}

		// Check for request channel
		reqCh, ok := `)
//line services_server_go.qtpl:262
	qw422016.E().S(reqChName)
//line services_server_go.qtpl:262
	qw422016.N().S(`.Load(msg.Reply)
		if !ok {
			reqCh = make(chan *`)
//line services_server_go.qtpl:264
	qw422016.N().S(inputName)
//line services_server_go.qtpl:264
	qw422016.N().S(`)
			`)
//line services_server_go.qtpl:265
	qw422016.E().S(reqChName)
//line services_server_go.qtpl:265
	qw422016.N().S(`.Store(msg.Reply, reqCh)

			go func() {
				defer sendEOF(msg)

				resCh := make(chan *`)
//line services_server_go.qtpl:270
	qw422016.E().S(method.OutputType.Original)
//line services_server_go.qtpl:270
	qw422016.N().S(`)
				errCh := make(chan error)

				go func() {
					for {
						select {
						case res, ok := <-resCh:
							if !ok {
								return
							}
							sendSuccess(msg, res)
						case err := <-errCh:
							sendError(msg, err)
							return
						}
					}
				}()
				if err := runner.service.`)
//line services_server_go.qtpl:287
	qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:287
	qw422016.N().S(`(context.Background(), reqCh, resCh, errCh); err != nil {
					sendError(msg, err)
					return
				}
			}()
		}
		reqCh <- req
	})
`)
//line services_server_go.qtpl:295
}

//line services_server_go.qtpl:295
func writegoServerBidiStreamHandler(qq422016 qtio422016.Writer, subjectName string, method *methodTmplData) {
//line services_server_go.qtpl:295
	qw422016 := qt422016.AcquireWriter(qq422016)
//line services_server_go.qtpl:295
	streamgoServerBidiStreamHandler(qw422016, subjectName, method)
//line services_server_go.qtpl:295
	qt422016.ReleaseWriter(qw422016)
//line services_server_go.qtpl:295
}

//line services_server_go.qtpl:295
func goServerBidiStreamHandler(subjectName string, method *methodTmplData) string {
//line services_server_go.qtpl:295
	qb422016 := qt422016.AcquireByteBuffer()
//line services_server_go.qtpl:295
	writegoServerBidiStreamHandler(qb422016, subjectName, method)
//line services_server_go.qtpl:295
	qs422016 := string(qb422016.B)
//line services_server_go.qtpl:295
	qt422016.ReleaseByteBuffer(qb422016)
//line services_server_go.qtpl:295
	return qs422016
//line services_server_go.qtpl:295
}
