// Code generated by qtc from "services_server_go.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line services_server_go.qtpl:1
package natsrpc

//line services_server_go.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line services_server_go.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line services_server_go.qtpl:1
func streamgoServerTemplate(qw422016 *qt422016.Writer, pkg *packageTmplData) {
//line services_server_go.qtpl:1
	qw422016.N().S(`
// Code generated by protoc-gen-go-nrpc. DO NOT EDIT.

package `)
//line services_server_go.qtpl:4
	qw422016.E().S(pkg.PackageName.Snake)
//line services_server_go.qtpl:4
	qw422016.N().S(`

import (
    "context"
    "errors"
    "fmt"
    "log"

    "github.com/nats-io/nats.go"
    "google.golang.org/protobuf/proto"
    "gopkg.in/typ.v4/sync2"
)

`)
//line services_server_go.qtpl:17
	for _, service := range pkg.Services {
//line services_server_go.qtpl:19
		nsp := service.Name.Pascal

//line services_server_go.qtpl:20
		qw422016.N().S(`
type `)
//line services_server_go.qtpl:22
		qw422016.E().S(nsp)
//line services_server_go.qtpl:22
		qw422016.N().S(`Service interface {
    OnClose() error

    //#region Methods
`)
//line services_server_go.qtpl:26
		for _, method := range service.Methods {
//line services_server_go.qtpl:28
			cs := method.IsClientStreaming
			ss := method.IsServerStreaming

//line services_server_go.qtpl:31
			switch {
//line services_server_go.qtpl:32
			case !cs && !ss:
//line services_server_go.qtpl:32
				qw422016.N().S(`            `)
//line services_server_go.qtpl:33
				qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:33
				qw422016.N().S(`(ctx context.Context, req *`)
//line services_server_go.qtpl:33
				qw422016.E().S(method.InputType.Original)
//line services_server_go.qtpl:33
				qw422016.N().S(`) (res *`)
//line services_server_go.qtpl:33
				qw422016.E().S(method.OutputType.Original)
//line services_server_go.qtpl:33
				qw422016.N().S(`, err error)
`)
//line services_server_go.qtpl:34
			case cs && !ss:
//line services_server_go.qtpl:34
				qw422016.N().S(`            `)
//line services_server_go.qtpl:35
				qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:35
				qw422016.N().S(`(ctx context.Context, reqCh <-chan *`)
//line services_server_go.qtpl:35
				qw422016.E().S(method.InputType.Original)
//line services_server_go.qtpl:35
				qw422016.N().S(`) (res *`)
//line services_server_go.qtpl:35
				qw422016.E().S(method.OutputType.Original)
//line services_server_go.qtpl:35
				qw422016.N().S(`, err error)
`)
//line services_server_go.qtpl:36
			case !cs && ss:
//line services_server_go.qtpl:36
				qw422016.N().S(`            `)
//line services_server_go.qtpl:37
				qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:37
				qw422016.N().S(`(ctx context.Context, req *`)
//line services_server_go.qtpl:37
				qw422016.E().S(method.InputType.Original)
//line services_server_go.qtpl:37
				qw422016.N().S(`, resCh <-chan *`)
//line services_server_go.qtpl:37
				qw422016.E().S(method.OutputType.Original)
//line services_server_go.qtpl:37
				qw422016.N().S(`, errCh <-chan error)
`)
//line services_server_go.qtpl:38
			case cs && ss:
//line services_server_go.qtpl:38
				qw422016.N().S(`            `)
//line services_server_go.qtpl:39
				qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:39
				qw422016.N().S(`(ctx context.Context, reqCh <-chan *`)
//line services_server_go.qtpl:39
				qw422016.E().S(method.InputType.Original)
//line services_server_go.qtpl:39
				qw422016.N().S(`, resCh chan<- *`)
//line services_server_go.qtpl:39
				qw422016.E().S(method.OutputType.Original)
//line services_server_go.qtpl:39
				qw422016.N().S(`, errCh chan<- error) error
`)
//line services_server_go.qtpl:40
			}
//line services_server_go.qtpl:41
		}
//line services_server_go.qtpl:41
		qw422016.N().S(`    //#endregion
}

const (
    `)
//line services_server_go.qtpl:46
		qw422016.E().S(nsp)
//line services_server_go.qtpl:46
		qw422016.N().S(`ServiceSubject = "`)
//line services_server_go.qtpl:46
		qw422016.E().S(service.Subject)
//line services_server_go.qtpl:46
		qw422016.N().S(`"
`)
//line services_server_go.qtpl:47
		for _, method := range service.Methods {
//line services_server_go.qtpl:47
			qw422016.N().S(`       `)
//line services_server_go.qtpl:48
			qw422016.E().S(nsp)
//line services_server_go.qtpl:48
			qw422016.N().S(`Service`)
//line services_server_go.qtpl:48
			qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:48
			qw422016.N().S(`Subject = "`)
//line services_server_go.qtpl:48
			qw422016.E().S(method.Subject)
//line services_server_go.qtpl:48
			qw422016.N().S(`"
`)
//line services_server_go.qtpl:49
		}
//line services_server_go.qtpl:49
		qw422016.N().S(`)

type `)
//line services_server_go.qtpl:52
		qw422016.E().S(nsp)
//line services_server_go.qtpl:52
		qw422016.N().S(`ServiceRunner struct {
    baseSubject string
    service `)
//line services_server_go.qtpl:54
		qw422016.E().S(nsp)
//line services_server_go.qtpl:54
		qw422016.N().S(`Service
    nc *nats.Conn
}

func New`)
//line services_server_go.qtpl:58
		qw422016.E().S(nsp)
//line services_server_go.qtpl:58
		qw422016.N().S(`ServiceRunner(nc *nats.Conn, service `)
//line services_server_go.qtpl:58
		qw422016.E().S(nsp)
//line services_server_go.qtpl:58
		qw422016.N().S(`Service) (*`)
//line services_server_go.qtpl:58
		qw422016.E().S(nsp)
//line services_server_go.qtpl:58
		qw422016.N().S(`ServiceRunner, error) {
    runner := &`)
//line services_server_go.qtpl:59
		qw422016.E().S(nsp)
//line services_server_go.qtpl:59
		qw422016.N().S(`ServiceRunner{
        service: service,
        nc: nc,
    }

`)
//line services_server_go.qtpl:64
		for _, method := range service.Methods {
//line services_server_go.qtpl:66
			subjectName := nsp + "Service" + method.Name.Pascal + "Subject"
			ss, cs := method.IsServerStreaming, method.IsClientStreaming

//line services_server_go.qtpl:70
			switch {
//line services_server_go.qtpl:71
			case !cs && !ss:
//line services_server_go.qtpl:71
				qw422016.N().S(`            `)
//line services_server_go.qtpl:72
				streamgoServerUnaryHandler(qw422016, subjectName, method)
//line services_server_go.qtpl:72
				qw422016.N().S(`
`)
//line services_server_go.qtpl:73
			case cs && !ss:
//line services_server_go.qtpl:73
				qw422016.N().S(`            `)
//line services_server_go.qtpl:74
				streamgoServerClientStreamHandler(qw422016, subjectName, method)
//line services_server_go.qtpl:74
				qw422016.N().S(`
`)
//line services_server_go.qtpl:75
			case !cs && ss:
//line services_server_go.qtpl:75
				qw422016.N().S(`            `)
//line services_server_go.qtpl:76
				streamgoServerServerStreamHandler(qw422016, subjectName, method)
//line services_server_go.qtpl:76
				qw422016.N().S(`
`)
//line services_server_go.qtpl:77
			case cs && ss:
//line services_server_go.qtpl:77
				qw422016.N().S(`            `)
//line services_server_go.qtpl:78
				streamgoServerBidiStreamHandler(qw422016, subjectName, method)
//line services_server_go.qtpl:78
				qw422016.N().S(`
`)
//line services_server_go.qtpl:79
			}
//line services_server_go.qtpl:80
		}
//line services_server_go.qtpl:80
		qw422016.N().S(`
    return runner,nil
}

func (runner *`)
//line services_server_go.qtpl:85
		qw422016.E().S(nsp)
//line services_server_go.qtpl:85
		qw422016.N().S(`ServiceRunner) Close() error {
    var errs []error
    if runner.service != nil {
        if err := runner.service.OnClose(); err != nil {
            errs = append(errs, err)
        }
    }

    if err := errors.Join(errs...); err != nil {
        return fmt.Errorf("failed to close runner: %w", err)
    }

    return nil
}

`)
//line services_server_go.qtpl:100
	}
//line services_server_go.qtpl:100
	qw422016.N().S(`
`)
//line services_server_go.qtpl:102
}

//line services_server_go.qtpl:102
func writegoServerTemplate(qq422016 qtio422016.Writer, pkg *packageTmplData) {
//line services_server_go.qtpl:102
	qw422016 := qt422016.AcquireWriter(qq422016)
//line services_server_go.qtpl:102
	streamgoServerTemplate(qw422016, pkg)
//line services_server_go.qtpl:102
	qt422016.ReleaseWriter(qw422016)
//line services_server_go.qtpl:102
}

//line services_server_go.qtpl:102
func goServerTemplate(pkg *packageTmplData) string {
//line services_server_go.qtpl:102
	qb422016 := qt422016.AcquireByteBuffer()
//line services_server_go.qtpl:102
	writegoServerTemplate(qb422016, pkg)
//line services_server_go.qtpl:102
	qs422016 := string(qb422016.B)
//line services_server_go.qtpl:102
	qt422016.ReleaseByteBuffer(qb422016)
//line services_server_go.qtpl:102
	return qs422016
//line services_server_go.qtpl:102
}

//line services_server_go.qtpl:105
func streamgoServerUnaryHandler(qw422016 *qt422016.Writer, subjectName string, method *methodTmplData) {
//line services_server_go.qtpl:105
	qw422016.N().S(`
// Unary call for `)
//line services_server_go.qtpl:106
	qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:106
	qw422016.N().S(`
nc.Subscribe(`)
//line services_server_go.qtpl:107
	qw422016.E().S(subjectName)
//line services_server_go.qtpl:107
	qw422016.N().S(`, func(msg *nats.Msg) {
        req := &`)
//line services_server_go.qtpl:108
	qw422016.E().S(method.InputType.Original)
//line services_server_go.qtpl:108
	qw422016.N().S(`{}
		if err := proto.Unmarshal(msg.Data, req); err != nil {
			sendError(msg, fmt.Errorf("failed to unmarshal request: %w", err))
			return
		}

		res, err := runner.service.`)
//line services_server_go.qtpl:114
	qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:114
	qw422016.N().S(`(context.Background(),req)
		if err != nil {
			sendError(msg, err)
			return
		}
		sendSuccess(msg, res)
	})
`)
//line services_server_go.qtpl:121
}

//line services_server_go.qtpl:121
func writegoServerUnaryHandler(qq422016 qtio422016.Writer, subjectName string, method *methodTmplData) {
//line services_server_go.qtpl:121
	qw422016 := qt422016.AcquireWriter(qq422016)
//line services_server_go.qtpl:121
	streamgoServerUnaryHandler(qw422016, subjectName, method)
//line services_server_go.qtpl:121
	qt422016.ReleaseWriter(qw422016)
//line services_server_go.qtpl:121
}

//line services_server_go.qtpl:121
func goServerUnaryHandler(subjectName string, method *methodTmplData) string {
//line services_server_go.qtpl:121
	qb422016 := qt422016.AcquireByteBuffer()
//line services_server_go.qtpl:121
	writegoServerUnaryHandler(qb422016, subjectName, method)
//line services_server_go.qtpl:121
	qs422016 := string(qb422016.B)
//line services_server_go.qtpl:121
	qt422016.ReleaseByteBuffer(qb422016)
//line services_server_go.qtpl:121
	return qs422016
//line services_server_go.qtpl:121
}

//line services_server_go.qtpl:123
func streamgoServerClientStreamHandler(qw422016 *qt422016.Writer, subjectName string, method *methodTmplData) {
//line services_server_go.qtpl:123
	qw422016.N().S(`
`)
//line services_server_go.qtpl:125
	reqChName := method.Name.Camel + "ClientReqChs"
	inputName := method.InputType.Original

//line services_server_go.qtpl:127
	qw422016.N().S(`
// Client streaming call for `)
//line services_server_go.qtpl:128
	qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:128
	qw422016.N().S(`
`)
//line services_server_go.qtpl:129
	qw422016.E().S(reqChName)
//line services_server_go.qtpl:129
	qw422016.N().S(` := sync2.Map[string, chan *`)
//line services_server_go.qtpl:129
	qw422016.N().S(inputName)
//line services_server_go.qtpl:129
	qw422016.N().S(`]{}
nc.Subscribe(`)
//line services_server_go.qtpl:130
	qw422016.E().S(subjectName)
//line services_server_go.qtpl:130
	qw422016.N().S(`, func(msg *nats.Msg) {
		// Check for end of stream
		if len(msg.Data) == 0 {
			log.Printf("Got EOF")
			reqCh, ok := `)
//line services_server_go.qtpl:134
	qw422016.E().S(reqChName)
//line services_server_go.qtpl:134
	qw422016.N().S(`.Load(msg.Reply)
			if !ok {
				sendError(msg, errors.New("no request channel found"))
				return
			}
			close(reqCh)
			`)
//line services_server_go.qtpl:140
	qw422016.E().S(reqChName)
//line services_server_go.qtpl:140
	qw422016.N().S(`.Delete(msg.Reply)
			return
		}

		// Check for request
		req := &`)
//line services_server_go.qtpl:145
	qw422016.N().S(inputName)
//line services_server_go.qtpl:145
	qw422016.N().S(`{}
		if err := proto.Unmarshal(msg.Data, req); err != nil {
			sendError(msg, fmt.Errorf("failed to unmarshal request: %w", err))
			return
		}

		log.Printf("Got request: %v", req)

		// Check for request channel
		reqCh, ok := `)
//line services_server_go.qtpl:154
	qw422016.E().S(reqChName)
//line services_server_go.qtpl:154
	qw422016.N().S(`.Load(msg.Reply)
		if !ok {
			reqCh = make(chan *`)
//line services_server_go.qtpl:156
	qw422016.N().S(inputName)
//line services_server_go.qtpl:156
	qw422016.N().S(`)

			`)
//line services_server_go.qtpl:158
	qw422016.E().S(reqChName)
//line services_server_go.qtpl:158
	qw422016.N().S(`.Store(msg.Reply, reqCh)

			go func() {
				res, err := runner.service.`)
//line services_server_go.qtpl:161
	qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:161
	qw422016.N().S(`(context.Background(),reqCh)
				if err != nil {
					sendError(msg, err)
					return
				}
				sendSuccess(msg, res)
			}()
		}
		reqCh <- req
	})
`)
//line services_server_go.qtpl:171
}

//line services_server_go.qtpl:171
func writegoServerClientStreamHandler(qq422016 qtio422016.Writer, subjectName string, method *methodTmplData) {
//line services_server_go.qtpl:171
	qw422016 := qt422016.AcquireWriter(qq422016)
//line services_server_go.qtpl:171
	streamgoServerClientStreamHandler(qw422016, subjectName, method)
//line services_server_go.qtpl:171
	qt422016.ReleaseWriter(qw422016)
//line services_server_go.qtpl:171
}

//line services_server_go.qtpl:171
func goServerClientStreamHandler(subjectName string, method *methodTmplData) string {
//line services_server_go.qtpl:171
	qb422016 := qt422016.AcquireByteBuffer()
//line services_server_go.qtpl:171
	writegoServerClientStreamHandler(qb422016, subjectName, method)
//line services_server_go.qtpl:171
	qs422016 := string(qb422016.B)
//line services_server_go.qtpl:171
	qt422016.ReleaseByteBuffer(qb422016)
//line services_server_go.qtpl:171
	return qs422016
//line services_server_go.qtpl:171
}

//line services_server_go.qtpl:173
func streamgoServerServerStreamHandler(qw422016 *qt422016.Writer, subjectName string, method *methodTmplData) {
//line services_server_go.qtpl:173
	qw422016.N().S(`
// Server streaming call for `)
//line services_server_go.qtpl:174
	qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:174
	qw422016.N().S(`
nc.Subscribe(`)
//line services_server_go.qtpl:175
	qw422016.E().S(subjectName)
//line services_server_go.qtpl:175
	qw422016.N().S(`, func(msg *nats.Msg) {
    req := &`)
//line services_server_go.qtpl:176
	qw422016.E().S(method.InputType.Original)
//line services_server_go.qtpl:176
	qw422016.N().S(`{}
    if err := proto.Unmarshal(msg.Data, req); err != nil {
        sendError(msg, fmt.Errorf("failed to unmarshal request: %w", err))
        return
    }

	resCh := make(chan *`)
//line services_server_go.qtpl:182
	qw422016.E().S(method.OutputType.Original)
//line services_server_go.qtpl:182
	qw422016.N().S(`)
	errCh := make(chan error)

	// User defined handler
	go runner.service.`)
//line services_server_go.qtpl:186
	qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:186
	qw422016.N().S(`(context.Background(), req, resCh, errCh)

	// Send responses to client
	go func () {
		defer sendEOF(msg)
		for {
			select {
			case res, ok := <-resCh:
				if !ok {
					return
				}
				sendSuccess(msg, res)
			case err := <-errCh:
				if err == nil {
					return
				}
				sendError(msg, err)
				return
			}
		}
	}()
})
`)
//line services_server_go.qtpl:208
}

//line services_server_go.qtpl:208
func writegoServerServerStreamHandler(qq422016 qtio422016.Writer, subjectName string, method *methodTmplData) {
//line services_server_go.qtpl:208
	qw422016 := qt422016.AcquireWriter(qq422016)
//line services_server_go.qtpl:208
	streamgoServerServerStreamHandler(qw422016, subjectName, method)
//line services_server_go.qtpl:208
	qt422016.ReleaseWriter(qw422016)
//line services_server_go.qtpl:208
}

//line services_server_go.qtpl:208
func goServerServerStreamHandler(subjectName string, method *methodTmplData) string {
//line services_server_go.qtpl:208
	qb422016 := qt422016.AcquireByteBuffer()
//line services_server_go.qtpl:208
	writegoServerServerStreamHandler(qb422016, subjectName, method)
//line services_server_go.qtpl:208
	qs422016 := string(qb422016.B)
//line services_server_go.qtpl:208
	qt422016.ReleaseByteBuffer(qb422016)
//line services_server_go.qtpl:208
	return qs422016
//line services_server_go.qtpl:208
}

//line services_server_go.qtpl:210
func streamgoServerBidiStreamHandler(qw422016 *qt422016.Writer, subjectName string, method *methodTmplData) {
//line services_server_go.qtpl:210
	qw422016.N().S(`
`)
//line services_server_go.qtpl:212
	reqChName := method.Name.Camel + "BiReqChs"
	inputName := method.InputType.Original

//line services_server_go.qtpl:214
	qw422016.N().S(`
// Bidirectional streaming call for `)
//line services_server_go.qtpl:215
	qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:215
	qw422016.N().S(`
`)
//line services_server_go.qtpl:216
	qw422016.E().S(reqChName)
//line services_server_go.qtpl:216
	qw422016.N().S(` := sync2.Map[string, chan *`)
//line services_server_go.qtpl:216
	qw422016.N().S(inputName)
//line services_server_go.qtpl:216
	qw422016.N().S(`]{}
nc.Subscribe(`)
//line services_server_go.qtpl:217
	qw422016.E().S(subjectName)
//line services_server_go.qtpl:217
	qw422016.N().S(`, func(msg *nats.Msg) {
		// Check for end of stream
		if len(msg.Data) == 0 {
			reqCh, ok := `)
//line services_server_go.qtpl:220
	qw422016.E().S(reqChName)
//line services_server_go.qtpl:220
	qw422016.N().S(`.Load(msg.Reply)
			if !ok {
				sendError(msg, errors.New("no request channel found"))
				return
			}
			close(reqCh)
			`)
//line services_server_go.qtpl:226
	qw422016.E().S(reqChName)
//line services_server_go.qtpl:226
	qw422016.N().S(`.Delete(msg.Reply)
			return
		}

		// Check for request
		req := &`)
//line services_server_go.qtpl:231
	qw422016.N().S(inputName)
//line services_server_go.qtpl:231
	qw422016.N().S(`{}
		if err := proto.Unmarshal(msg.Data, req); err != nil {
			sendError(msg, fmt.Errorf("failed to unmarshal request: %w", err))
			return
		}

		// Check for request channel
		reqCh, ok := `)
//line services_server_go.qtpl:238
	qw422016.E().S(reqChName)
//line services_server_go.qtpl:238
	qw422016.N().S(`.Load(msg.Reply)
		if !ok {
			reqCh = make(chan *`)
//line services_server_go.qtpl:240
	qw422016.N().S(inputName)
//line services_server_go.qtpl:240
	qw422016.N().S(`)
			`)
//line services_server_go.qtpl:241
	qw422016.E().S(reqChName)
//line services_server_go.qtpl:241
	qw422016.N().S(`.Store(msg.Reply, reqCh)

			go func() {
				defer sendEOF(msg)

				resCh := make(chan *`)
//line services_server_go.qtpl:246
	qw422016.E().S(method.OutputType.Original)
//line services_server_go.qtpl:246
	qw422016.N().S(`)
				errCh := make(chan error)

				go func() {
					for {
						select {
						case res, ok := <-resCh:
							if !ok {
								return
							}
							sendSuccess(msg, res)
						case err := <-errCh:
							sendError(msg, err)
							return
						}
					}
				}()
				if err := runner.service.`)
//line services_server_go.qtpl:263
	qw422016.E().S(method.Name.Pascal)
//line services_server_go.qtpl:263
	qw422016.N().S(`(context.Background(), reqCh, resCh, errCh); err != nil {
					sendError(msg, err)
					return
				}
			}()
		}
		reqCh <- req
	})
`)
//line services_server_go.qtpl:271
}

//line services_server_go.qtpl:271
func writegoServerBidiStreamHandler(qq422016 qtio422016.Writer, subjectName string, method *methodTmplData) {
//line services_server_go.qtpl:271
	qw422016 := qt422016.AcquireWriter(qq422016)
//line services_server_go.qtpl:271
	streamgoServerBidiStreamHandler(qw422016, subjectName, method)
//line services_server_go.qtpl:271
	qt422016.ReleaseWriter(qw422016)
//line services_server_go.qtpl:271
}

//line services_server_go.qtpl:271
func goServerBidiStreamHandler(subjectName string, method *methodTmplData) string {
//line services_server_go.qtpl:271
	qb422016 := qt422016.AcquireByteBuffer()
//line services_server_go.qtpl:271
	writegoServerBidiStreamHandler(qb422016, subjectName, method)
//line services_server_go.qtpl:271
	qs422016 := string(qb422016.B)
//line services_server_go.qtpl:271
	qt422016.ReleaseByteBuffer(qb422016)
//line services_server_go.qtpl:271
	return qs422016
//line services_server_go.qtpl:271
}
